import { expect, test } from "@playwright/test";
import { fixture, user } from "./fixture";

  test("account navigation supports keyboard activation and mobile sidebar dismissal", async ({ page }) => {
    const { errors } = await fixture(page);
    await page.setViewportSize({ width: 390, height: 900 });
    await page.goto("/app");
    await page.getByRole("button", { name: "Menu", exact: true }).click();
    const toggle = page.getByLabel("Account menu", { exact: true });
    const account = page.getByRole("link", { name: "Account settings", exact: true });
    const settings = page.getByRole("link", { name: "Settings", exact: true });
    const fieldManagement = page.getByRole("link", { name: "Field management" });
    const importExport = page.getByRole("link", { name: "Import & export" });
    const integrations = page.getByRole("link", { name: "Webhooks & automations" });
    const docs = page.getByRole("link", { name: "API docs" });
    const help = page.getByRole("link", { name: "Help", exact: true });
    await expect(account).toBeHidden();
    await toggle.focus();
    await page.keyboard.press("Enter");
    await expect(account).toBeVisible();
    await expect(fieldManagement).toBeVisible();
    await expect(importExport).toBeVisible();
    await expect(integrations).toBeVisible();
    await expect(docs).toBeVisible();
    await expect(help).toBeVisible();
    await expect(page.getByRole("link", { name: "Administration", exact: true })).toBeVisible();
    await page.keyboard.press("Tab");
    await expect(account).toBeFocused();
    await page.keyboard.press("Tab");
    await expect(fieldManagement).toBeFocused();
    await page.keyboard.press("Tab");
    await expect(importExport).toBeFocused();
    await page.keyboard.press("Tab");
    await expect(integrations).toBeFocused();
    await page.keyboard.press("Tab");
    await expect(docs).toBeFocused();
    await page.keyboard.press("Tab");
    await expect(help).toBeFocused();
    await page.keyboard.press("Tab");
    await expect(settings).toBeFocused();
    await page.keyboard.press("Escape");
    await expect(account).toBeHidden();
    await expect(toggle).toBeFocused();
    await toggle.click();
    await page.getByRole("button", { name: "Menu", exact: true }).click();
    await expect(account).toBeHidden();
    await page.getByRole("button", { name: "Menu", exact: true }).click();
    await toggle.click();
    await help.click();
    await expect(page.getByRole("heading", { name: "Help", exact: true })).toBeVisible();
    expect(errors).toEqual([]);
  });

test("account menu hides administration for non-admins and preserves failed logout", async ({ page }) => {
  await fixture(page);
  await page.route("**/api/v1/auth/me", route => route.fulfill({ json: { ...user, isAdmin: false } }));
  await page.route("**/api/v1/auth/logout", route => route.fulfill({ status: 503, json: { error: "Sign out unavailable" } }));
  await page.goto("/app");
  await page.getByLabel("Account menu", { exact: true }).click();
  await expect(page.getByRole("link", { name: "Administration", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page.getByRole("alert")).toContainText("Sign out unavailable");
  await expect(page.getByRole("button", { name: "Sign out", exact: true })).toBeEnabled();
});
