// Hand-maintained OpenAPI 3.1 description of the REST surface. The spec is
// served at /api/v1/openapi.json and rendered by the Docs page.
import { Effect } from 'effect'
import { events, providerTypes } from './automations.js'
import { permissions } from './types.js'

type Schema = Record<string, unknown>
const ref = (name: string): Schema => ({ $ref: `#/components/schemas/${name}` })
const str = (extra: Schema = {}): Schema => ({ type: 'string', ...extra })
const uuid = (): Schema => str({ format: 'uuid' })
const timestamp = (): Schema => str({ format: 'date-time' })
const nullable = (schema: Schema): Schema => ({ anyOf: [schema, { type: 'null' }] })
const array = (items: Schema, extra: Schema = {}): Schema => ({ type: 'array', items, ...extra })
const object = (properties: Record<string, Schema> = {}, required: string[] = [], extra: Schema = {}): Schema => ({
  type: 'object', properties, ...(required.length ? { required } : {}), ...extra,
})
const body = (schema: Schema, example?: unknown) => ({
  required: true,
  content: { 'application/json': { schema, ...(example === undefined ? {} : { example }) } },
})
const response = (description: string, schema?: Schema, example?: unknown) => ({
  description,
  ...(schema ? { content: { 'application/json': { schema, ...(example === undefined ? {} : { example }) } } } : {}),
})
const ok = (schema: Schema, example?: unknown) => response('Success', schema, example)
const error = (description = 'Request rejected') => response(description, ref('Error'), { error: description })
const success = ref('Success')
const pathId = (name: string, description?: string) => ({ name, in: 'path', required: true, ...(description ? { description } : {}), schema: uuid() })
const query = (name: string, schema: Schema, description?: string) => ({ name, in: 'query', required: false, ...(description ? { description } : {}), schema })
const auth = [{ bearer: [] }, { session: [] }]
const secured = (permission?: string) => permission
  ? `Requires the workspace \`${permission}\` permission. Workspace and resource identifiers are revalidated against the authenticated user.`
  : 'Requires an authenticated account.'

const event = str({ enum: [...events] })
const priority = str({ enum: ['none', 'low', 'medium', 'high', 'urgent'] })
const nodeIcon = nullable(str({ enum: ['diamond', 'briefcase', 'target', 'folder', 'archive', 'bookmark', 'list', 'checklist', 'calendar', 'flag'] }))
const nodeColor = nullable(str({ enum: ['slate', 'orange', 'amber', 'green', 'teal', 'blue', 'violet', 'rose'] }))
const date = nullable(str({ format: 'date', pattern: '^\\d{4}-\\d{2}-\\d{2}$' }))
const hexColor = str({ pattern: '^#[0-9a-fA-F]{6}$', example: '#2f7d32' })
const action = { oneOf: [
  object({ type: { type: 'string', const: 'webhook' }, config: object({ url: str({ format: 'uri', maxLength: 2000 }), method: str({ enum: ['POST', 'PUT', 'PATCH'], default: 'POST' }) }, ['url'], { additionalProperties: false }) }, ['type', 'config'], { additionalProperties: false }),
  object({ type: { type: 'string', const: 'email' }, config: object({ to: array(str({ format: 'email', maxLength: 254 }), { minItems: 1, maxItems: 10 }), subject: str({ minLength: 1, maxLength: 200 }) }, ['to', 'subject'], { additionalProperties: false }) }, ['type', 'config'], { additionalProperties: false }),
  object({ type: { type: 'string', const: 'http' }, config: object({ url: str({ format: 'uri', maxLength: 2000 }), method: str({ enum: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'], default: 'POST' }), headers: object({}, [], { maxProperties: 20, additionalProperties: str({ maxLength: 2000 }) }), body: str({ maxLength: 20000 }) }, ['url'], { additionalProperties: false }) }, ['type', 'config'], { additionalProperties: false }),
  object({ type: { type: 'string', const: 'log' }, config: object({ message: str({ maxLength: 2000 }) }, ['message'], { additionalProperties: false }) }, ['type', 'config'], { additionalProperties: false }),
] }
const actionExamples = [
  { type: 'log', config: { message: 'Task event received' } },
  { type: 'http', config: { url: 'https://hooks.example.test/tasks', method: 'POST', headers: { 'x-source': 'hopya' }, body: '{{event}}' } },
]
const itemInputProperties: Record<string, Schema> = {
  nodeId: uuid(), title: str({ minLength: 1, maxLength: 300 }), description: str({ maxLength: 50000, default: '' }),
  status: str({ minLength: 1, maxLength: 64 }), priority, startDate: date, dueDate: date,
  tags: array(str({ minLength: 1, maxLength: 60 }), { maxItems: 30 }), customFields: object({}, [], { maxProperties: 100, additionalProperties: { anyOf: [str({ maxLength: 10000 }), { type: 'number' }, { type: 'boolean' }, array(str({ minLength: 1, maxLength: 120 }), { maxItems: 100 }), { type: 'null' }] } }),
  assigneeId: nullable(uuid()), checklist: array(object({ id: str({ maxLength: 100 }), text: str({ maxLength: 400 }), done: { type: 'boolean' } }, ['text'], { additionalProperties: false }), { maxItems: 100 }), parentId: nullable(uuid()),
}
const listSortSchema = nullable(object({ column: str({ maxLength: 43 }), direction: str({ enum: ['asc', 'desc'] }) }, ['column', 'direction'], { additionalProperties: false }))
const tagColorsMap = object({}, [], { maxProperties: 30, additionalProperties: hexColor })

const schemas = {
  Error: object({ error: str() }, ['error'], { additionalProperties: false }),
  Success: object({ success: { type: 'boolean', const: true } }, ['success'], { additionalProperties: false }),
  User: object({ id: uuid(), name: str({ maxLength: 120 }), email: str({ format: 'email' }), isAdmin: { type: 'boolean' } }, ['id', 'name', 'email', 'isAdmin']),
  AdminUser: object({ id: uuid(), name: str(), email: str({ format: 'email' }), isAdmin: { type: 'boolean' }, disabled: { type: 'boolean' }, createdAt: timestamp() }, ['id', 'name', 'email', 'isAdmin', 'disabled', 'createdAt']),
  Workspace: object({ id: uuid(), name: str({ maxLength: 120 }), createdAt: timestamp() }, ['id', 'name', 'createdAt']),
  ChecklistEntry: object({ id: uuid(), text: str({ maxLength: 200 }), done: { type: 'boolean' } }, ['id', 'text', 'done']),
  Item: object({
    id: uuid(), workspaceId: uuid(), nodeId: uuid(), title: str({ maxLength: 300 }), description: str({ maxLength: 50000 }),
    status: str({ minLength: 1, maxLength: 64 }), priority, startDate: date, dueDate: date,
    tags: array(str({ maxLength: 60 }), { maxItems: 30 }), customFields: object({}, [], { additionalProperties: true }),
    assigneeId: nullable(uuid()), checklist: array(ref('ChecklistEntry'), { maxItems: 100 }), parentId: nullable(uuid()), archivedAt: nullable(timestamp()),
    createdAt: timestamp(), updatedAt: timestamp(),
  }, ['id', 'workspaceId', 'nodeId', 'title', 'description', 'status', 'priority', 'startDate', 'dueDate', 'tags', 'customFields', 'assigneeId', 'checklist', 'parentId', 'archivedAt', 'createdAt', 'updatedAt']),
  ItemCreate: object(itemInputProperties, ['nodeId', 'title'], { additionalProperties: false }),
  ItemPatch: object({ ...itemInputProperties, expectedUpdatedAt: timestamp() }, [], { additionalProperties: false }),
  Node: object({
    id: uuid(), workspaceId: uuid(), name: str({ maxLength: 120 }), description: str({ maxLength: 50000 }),
    kind: str({ enum: ['project', 'folder', 'list'] }), parentId: nullable(uuid()), icon: nodeIcon, color: nodeColor, createdAt: timestamp(),
  }, ['id', 'workspaceId', 'name', 'description', 'kind', 'parentId', 'icon', 'color', 'createdAt']),
  NodeCreate: object({ name: str({ minLength: 1, maxLength: 120 }), description: str({ maxLength: 50000 }), kind: str({ enum: ['project', 'folder', 'list'] }), parentId: nullable(uuid()), icon: nodeIcon, color: nodeColor }, ['name', 'kind'], { additionalProperties: false }),
  NodePatch: object({ name: str({ minLength: 1, maxLength: 120 }), description: str({ maxLength: 50000 }), parentId: nullable(uuid()), expectedParentId: nullable(uuid()), icon: nodeIcon, color: nodeColor }, [], { additionalProperties: false, anyOf: [{ required: ['name'] }, { required: ['description'] }, { required: ['parentId'] }, { required: ['icon'] }, { required: ['color'] }], dependentRequired: { expectedParentId: ['parentId'] } }),
  FieldSettings: object({ dateFormat: str({ enum: ['yyyy-MM-dd', 'MMM d, yyyy', 'MMMM d, yyyy', 'dd/MM/yyyy'] }), maxRating: { type: 'integer', minimum: 1, maximum: 10 }, formula: str({ minLength: 1, maxLength: 200 }) }, [], { additionalProperties: false }),
  Field: object({ id: uuid(), workspaceId: uuid(), name: str({ maxLength: 120 }), type: str({ enum: ['text', 'number', 'date', 'datetime', 'checkbox', 'select', 'checklist', 'rating', 'formula'] }), options: array(str({ maxLength: 120 }), { maxItems: 100 }), settings: ref('FieldSettings') }, ['id', 'workspaceId', 'name', 'type', 'options']),
  FieldCreate: object({ name: str({ minLength: 1, maxLength: 120 }), type: str({ enum: ['text', 'number', 'date', 'datetime', 'checkbox', 'select', 'checklist', 'rating', 'formula'] }), options: array(str({ minLength: 1, maxLength: 120 }), { maxItems: 100 }), settings: ref('FieldSettings'), projectId: uuid() }, ['name', 'type'], { additionalProperties: false }),
  FieldPatch: object({ name: str({ minLength: 1, maxLength: 120 }), options: array(str({ minLength: 1, maxLength: 120 }), { maxItems: 100 }), settings: ref('FieldSettings') }, [], { additionalProperties: false, minProperties: 1 }),
  Status: object({ id: str({ minLength: 1, maxLength: 64, pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$' }), name: str({ minLength: 1, maxLength: 120 }), color: hexColor, completed: { type: 'boolean' } }, ['id', 'name', 'color', 'completed'], { additionalProperties: false }),
  ProjectFields: object({ projectId: uuid(), fieldIds: array(uuid(), { maxItems: 100, uniqueItems: true }), builtInFields: array(str({ enum: ['priority', 'startDate', 'tags', 'description', 'nodeId', 'createdAt', 'updatedAt'] }), { maxItems: 7, uniqueItems: true }), statuses: array(ref('Status'), { minItems: 1, maxItems: 50 }), dateFormat: str({ enum: ['yyyy-MM-dd', 'MMM d, yyyy', 'MMMM d, yyyy', 'dd/MM/yyyy'] }), updatedAt: timestamp() }, ['projectId', 'fieldIds', 'builtInFields', 'statuses', 'updatedAt']),
  ListStatuses: object({ listId: uuid(), statuses: array(ref('Status'), { minItems: 1, maxItems: 50 }), updatedAt: timestamp(), inheritedProjectUpdatedAt: timestamp() }, ['listId', 'updatedAt']),
  ListTagColors: object({ listId: uuid(), colors: tagColorsMap, updatedAt: timestamp() }, ['listId', 'colors', 'updatedAt']),
  ListViewSettings: object({ view: { type: 'string', const: 'list' }, projectId: nullable(uuid()), columnOrder: array(str({ maxLength: 43 }), { maxItems: 111, uniqueItems: true }), hiddenColumns: array(str({ maxLength: 43 }), { maxItems: 110, uniqueItems: true }), sort: listSortSchema, updatedAt: nullable(timestamp()) }, ['view', 'projectId', 'columnOrder', 'hiddenColumns', 'sort', 'updatedAt']),
  Role: object({ id: uuid(), workspaceId: uuid(), name: str({ maxLength: 120 }), permissions: array(str({ enum: [...permissions] }), { uniqueItems: true }), isOwner: { type: 'boolean' } }, ['id', 'workspaceId', 'name', 'permissions', 'isOwner']),
  Membership: object({ userId: uuid(), workspaceId: uuid(), roleId: uuid() }, ['userId', 'workspaceId', 'roleId']),
  Attachment: object({ id: uuid(), name: str({ maxLength: 255 }), size: { type: 'integer', minimum: 0 }, contentType: str({ maxLength: 127 }), createdAt: timestamp() }, ['id', 'name', 'size', 'contentType', 'createdAt']),
  CommentReaction: object({ emoji: str({ enum: ['👍', '❤️', '😂', '🎉', '😕', '👀'] }), count: { type: 'integer', minimum: 1 }, reactedByMe: { type: 'boolean' } }, ['emoji', 'count', 'reactedByMe']),
  Comment: object({ id: uuid(), workspaceId: uuid(), itemId: uuid(), authorId: nullable(uuid()), authorName: str({ maxLength: 120 }), body: str({ maxLength: 10000 }), parentId: nullable(uuid()), reactions: array(ref('CommentReaction'), { maxItems: 6 }), createdAt: timestamp(), deletedAt: nullable(timestamp()) }, ['id', 'workspaceId', 'itemId', 'authorId', 'authorName', 'body', 'parentId', 'reactions', 'createdAt', 'deletedAt']),
  Notification: object({ id: uuid(), workspaceId: uuid(), type: str({ enum: ['assignment', 'mention'] }), itemId: uuid(), itemTitle: str({ maxLength: 300 }), commentId: nullable(uuid()), actorId: nullable(uuid()), actorName: str({ maxLength: 120 }), createdAt: timestamp(), readAt: nullable(timestamp()) }, ['id', 'workspaceId', 'type', 'itemId', 'itemTitle', 'commentId', 'actorId', 'actorName', 'createdAt', 'readAt']),
  Webhook: object({ id: uuid(), name: str({ maxLength: 120 }), url: str({ format: 'uri', maxLength: 2000 }), events: array(event, { minItems: 1, maxItems: events.length }), enabled: { type: 'boolean' }, createdAt: timestamp(), updatedAt: timestamp() }, ['id', 'name', 'url', 'events', 'enabled', 'createdAt', 'updatedAt']),
  Action: { ...action, examples: actionExamples },
  Automation: object({ id: uuid(), workspaceId: uuid(), name: str({ maxLength: 120 }), event, version: { type: 'integer', minimum: 1 }, enabled: { type: 'boolean' }, steps: array(ref('Action'), { minItems: 1, maxItems: 20 }), action: ref('Action'), createdAt: timestamp(), updatedAt: timestamp() }, ['id', 'workspaceId', 'name', 'event', 'version', 'enabled', 'steps', 'createdAt', 'updatedAt']),
  AutomationInput: object({ name: str({ minLength: 1, maxLength: 120 }), event, action: ref('Action'), steps: array(ref('Action'), { minItems: 1, maxItems: 20 }), enabled: { type: 'boolean', default: true } }, ['name', 'event'], { additionalProperties: false, oneOf: [{ required: ['action'], not: { required: ['steps'] } }, { required: ['steps'], not: { required: ['action'] } }] }),
  AutomationPatch: object({ name: str({ minLength: 1, maxLength: 120 }), event, action: ref('Action'), steps: array(ref('Action'), { minItems: 1, maxItems: 20 }), enabled: { type: 'boolean' } }, [], { additionalProperties: false, not: { required: ['action', 'steps'] } }),
  StepRun: object({ id: uuid(), stepId: uuid(), position: { type: 'integer', minimum: 1 }, type: str({ enum: [...providerTypes] }), status: str({ enum: ['pending', 'running', 'delivered', 'failed', 'skipped'] }), output: str({ maxLength: 8192 }), log: str({ maxLength: 2000 }), startedAt: nullable(timestamp()), completedAt: nullable(timestamp()) }, ['id', 'stepId', 'position', 'type', 'status', 'output', 'log', 'startedAt', 'completedAt']),
  AutomationRun: object({ id: uuid(), workspaceId: uuid(), automationId: nullable(uuid()), targetType: str({ enum: ['automation', 'webhook'] }), targetId: uuid(), automationVersion: nullable({ type: 'integer', minimum: 1 }), status: str({ enum: ['pending', 'running', 'delivered', 'failed'] }), detail: str({ maxLength: 2000 }), createdAt: timestamp(), startedAt: nullable(timestamp()), completedAt: nullable(timestamp()), steps: array(ref('StepRun'), { maxItems: 20 }) }, ['id', 'workspaceId', 'automationId', 'targetType', 'targetId', 'automationVersion', 'status', 'detail', 'createdAt', 'startedAt', 'completedAt', 'steps']),
  OidcIdentity: object({ id: uuid(), userId: uuid(), issuer: str({ format: 'uri', maxLength: 2048 }), subject: str({ minLength: 1, maxLength: 255 }), createdAt: timestamp() }, ['id', 'userId', 'issuer', 'subject', 'createdAt']),
}

const workspaceTag = 'Workspaces'
const itemsTag = 'Tasks'
const structureTag = 'Structure & fields'
const automationsTag = 'Automations'
const adminTag = 'Accounts & admin'

function paths() {
  const wid = pathId('wid', 'Workspace ID; membership and the operation permission are checked server-side.')
  const itemFilters = [wid, query('nodeId', uuid(), 'Exact list ID.'), query('search', str({ maxLength: 300 }), 'Title/description search.'), query('status', str({ maxLength: 64 }), 'Exact effective status ID.'), query('archived', str({ enum: ['exclude', 'include', 'only'], default: 'exclude' }), 'Archived-task visibility.')]
  return {
    '/health': { get: { summary: 'Health probe', tags: ['Meta'], security: [], servers: [{ url: '/' }], responses: { '200': ok(object({ status: { type: 'string', const: 'ok' } }, ['status']), { status: 'ok' }) } } },
    '/config': { get: { summary: 'Public instance configuration', tags: ['Meta'], security: [], responses: { '200': ok(object({ landingEnabled: { type: 'boolean' }, logo: str(), registrationEnabled: { type: 'boolean' }, setupRequired: { type: 'boolean' }, ssoEnabled: { type: 'boolean' }, aiEnabled: { type: 'boolean' }, passwordResetEnabled: { type: 'boolean' } }, ['landingEnabled', 'registrationEnabled', 'setupRequired', 'ssoEnabled', 'aiEnabled', 'passwordResetEnabled'])) } } },
    '/openapi.json': { get: { summary: 'This OpenAPI 3.1 document', tags: ['Meta'], security: [], responses: { '200': response('OpenAPI JSON document', object()) } } },
    '/auth/setup': { post: { summary: 'Create the first site administrator', description: 'Public only while setup is incomplete. Requires the operator-provided setup token and creates an HttpOnly session.', tags: [adminTag], security: [], requestBody: body(object({ name: str({ maxLength: 120 }), email: str({ format: 'email', maxLength: 254 }), password: str({ minLength: 12, maxLength: 256, writeOnly: true }), setupToken: str({ maxLength: 512, writeOnly: true }) }, ['name', 'email', 'password', 'setupToken'], { additionalProperties: false }), { name: 'Administrator', email: 'admin@example.test', password: '[REDACTED]', setupToken: '[REDACTED]' }), responses: { '201': ok(ref('User')), '403': error('Setup not authorized'), '409': error('Setup already completed') } } },
    '/auth/register': { post: { summary: 'Register an account', description: 'Public only when registration is enabled and setup is complete. Creates an HttpOnly session.', tags: [adminTag], security: [], requestBody: body(object({ name: str({ maxLength: 120 }), email: str({ format: 'email', maxLength: 254 }), password: str({ minLength: 12, maxLength: 256, writeOnly: true }) }, ['name', 'email', 'password'], { additionalProperties: false }), { name: 'Example User', email: 'user@example.test', password: '[REDACTED]' }), responses: { '201': ok(ref('User')), '403': error('Registration is closed') } } },
    '/auth/login': { post: { summary: 'Password sign-in', tags: [adminTag], security: [], requestBody: body(object({ email: str({ format: 'email', maxLength: 254 }), password: str({ minLength: 1, maxLength: 256, writeOnly: true }) }, ['email', 'password'], { additionalProperties: false }), { email: 'user@example.test', password: '[REDACTED]' }), responses: { '200': ok(ref('User')), '401': error('Invalid email or password') } } },
    '/auth/forgot-password': { post: { summary: 'Request local password recovery', description: 'Always returns the same accepted response for valid email syntax. Delivery is available only when SMTP_URL and SMTP_FROM are configured.', tags: [adminTag], security: [], requestBody: body(object({ email: str({ format: 'email', maxLength: 254 }) }, ['email'], { additionalProperties: false }), { email: 'user@example.test' }), responses: { '202': ok(object({ message: str() }, ['message'])), '429': error('Too many authentication attempts') } } },
    '/auth/reset-password': { post: { summary: 'Complete local password recovery', description: 'Consumes a single-use 30-minute token and revokes all sessions and personal access tokens.', tags: [adminTag], security: [], requestBody: body(object({ token: str({ minLength: 43, maxLength: 43, writeOnly: true }), password: str({ minLength: 12, maxLength: 256, writeOnly: true }) }, ['token', 'password'], { additionalProperties: false }), { token: '[REDACTED]', password: '[REDACTED]' }), responses: { '200': ok(object({ success: { type: 'boolean' } }, ['success'])), '400': error('Password reset link is invalid or expired'), '429': error('Too many authentication attempts') } } },
    '/auth/sso': { get: { summary: 'Start an optional OIDC sign-in', description: 'Creates a short-lived HttpOnly PKCE flow cookie and redirects to the operator-configured issuer. No local account is selected by unverified email.', tags: [adminTag], security: [], responses: { '302': response('Redirect to the configured OIDC authorization endpoint'), '429': error('Too many SSO attempts'), '503': error('SSO is not configured') } } },
    '/auth/sso/callback': { get: { summary: 'Complete an optional OIDC sign-in', description: 'Validates and consumes the PKCE flow, then binds the verified issuer/subject identity. Auto-provisioning is separate and disabled by default.', tags: [adminTag], security: [], parameters: [query('code', str()), query('state', str({ maxLength: 256 })), query('error', str())], responses: { '302': response('Redirect to the authenticated application'), '401': error('SSO authentication failed'), '403': error('SSO identity is not linked to an account'), '409': error('SSO account requires administrator linking'), '503': error('SSO is not configured') } } },
    '/auth/logout': { post: { summary: 'Sign out and revoke the current session', description: secured(), tags: [adminTag], responses: { '200': ok(success, { success: true }), '401': error('Authentication required') } } },
    '/auth/me': { get: { summary: 'Current user', description: secured(), tags: [adminTag], responses: { '200': ok(ref('User')), '401': error('Authentication required') } } },
    '/auth/profile': { patch: { summary: 'Update profile or credentials', description: 'Requires authentication. Email and password changes require currentPassword and revoke other sessions and tokens.', tags: [adminTag], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }), email: str({ format: 'email', maxLength: 254 }), password: str({ minLength: 12, maxLength: 256, writeOnly: true }), currentPassword: str({ minLength: 1, maxLength: 256, writeOnly: true }) }, ['name'], { additionalProperties: false }), { name: 'Example User', email: 'user@example.test' }), responses: { '200': ok(ref('User')), '400': error('Invalid profile update'), '403': error('Current password is incorrect'), '409': error('Account changed or email is unavailable') } } },
    '/auth/tokens': {
      get: { summary: 'List API token metadata', description: secured(), tags: [adminTag], responses: { '200': ok(array(object({ id: uuid(), name: str(), createdAt: timestamp(), expiresAt: timestamp() }, ['id', 'name', 'createdAt', 'expiresAt']))) } },
      post: { summary: 'Create an API token', description: 'Requires authentication. The raw token is returned once and only its hash is stored.', tags: [adminTag], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }) }, ['name'], { additionalProperties: false }), { name: 'CLI on workstation' }), responses: { '201': ok(object({ token: str({ writeOnly: true }) }, ['token']), { token: '[REDACTED]' }), '409': error('Maximum active tokens reached') } },
    },
    '/auth/tokens/{id}': { delete: { summary: 'Revoke an API token', description: secured(), tags: [adminTag], parameters: [pathId('id', 'Token ID owned by the current account.')], responses: { '200': ok(success, { success: true }), '404': error('Token not found') } } },
    '/admin/users': {
      get: { summary: 'List accounts', description: 'Requires site administrator.', tags: [adminTag], responses: { '200': ok(array(ref('AdminUser'))), '403': error('Site administrator required') } },
      post: { summary: 'Create an account', description: 'Requires site administrator.', tags: [adminTag], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }), email: str({ format: 'email', maxLength: 254 }), password: str({ minLength: 12, maxLength: 256, writeOnly: true }), isAdmin: { type: 'boolean', default: false } }, ['name', 'email', 'password'], { additionalProperties: false }), { name: 'Example User', email: 'user@example.test', password: '[REDACTED]', isAdmin: false }), responses: { '201': ok(ref('AdminUser')), '403': error('Site administrator required') } },
    },
    '/admin/users/{id}': { patch: { summary: 'Change account admin or disabled flags', description: 'Requires site administrator. Disabling revokes credentials and clears task assignments; the last active administrator is protected.', tags: [adminTag], parameters: [pathId('id', 'Target user ID.')], requestBody: body(object({ isAdmin: { type: 'boolean' }, disabled: { type: 'boolean' } }, [], { additionalProperties: false, minProperties: 1 }), { disabled: true }), responses: { '200': ok(ref('AdminUser')), '404': error('User not found'), '409': error('Site must retain an active administrator') } } },
    '/admin/audit': { get: { summary: 'Audit log', description: 'Requires site administrator. Audit details are sanitized and do not include raw secrets or full AI prompts.', tags: [adminTag], parameters: [query('workspaceId', uuid()), query('limit', { type: 'integer', minimum: 1, maximum: 200, default: 50 }), query('offset', { type: 'integer', minimum: 0, maximum: 1000000, default: 0 })], responses: { '200': ok(array(object({}, [], { additionalProperties: true }))) } } },
    '/admin/status': { get: { summary: 'Instance status', description: 'Requires site administrator.', tags: [adminTag], responses: { '200': ok(object({}, [], { additionalProperties: true })) } } },
    '/admin/oidc-identities': {
      get: { summary: 'List linked OIDC identities', description: 'Requires site administrator. Returns issuer and subject binding metadata, never provider tokens.', tags: [adminTag], parameters: [query('userId', uuid(), 'Optional exact user filter.')], responses: { '200': ok(array(ref('OidcIdentity'))), '403': error('Site administrator required') } },
      post: { summary: 'Link an OIDC identity to an active account', description: 'Requires site administrator. Identity ownership is bound to exact issuer and subject, not email.', tags: [adminTag], requestBody: body(object({ userId: uuid(), issuer: str({ format: 'uri', minLength: 1, maxLength: 2048 }), subject: str({ minLength: 1, maxLength: 255 }) }, ['userId', 'issuer', 'subject'], { additionalProperties: false }), { userId: '11111111-1111-4111-8111-111111111111', issuer: 'https://id.example.test', subject: 'provider-subject-123' }), responses: { '201': ok(object({ id: uuid(), userId: uuid(), createdAt: timestamp() }, ['id', 'userId', 'createdAt'])), '400': error('Invalid OIDC identity'), '404': error('Active user not found'), '409': error('OIDC identity already linked') } },
    },
    '/admin/oidc-identities/{id}': { delete: { summary: 'Unlink an OIDC identity', description: 'Requires site administrator. Revokes all sessions and tokens for the target account and preserves its last configured login method.', tags: [adminTag], parameters: [pathId('id', 'OIDC identity ID.')], responses: { '200': ok(success, { success: true }), '404': error('OIDC identity not found'), '409': error('Cannot remove the last login method') } } },
    '/site/settings': {
      get: { summary: 'Read site settings', description: 'Requires site administrator.', tags: [adminTag], responses: { '200': ok(object({ landingDisabled: { type: 'boolean' }, logo: nullable(object({ updatedAt: timestamp(), url: str() }, ['updatedAt', 'url'])) }, ['landingDisabled', 'logo'])) } },
      patch: { summary: 'Update site settings', description: 'Requires site administrator.', tags: [adminTag], requestBody: body(object({ landingDisabled: { type: 'boolean' } }, [], { additionalProperties: false }), { landingDisabled: true }), responses: { '200': ok(object({ landingDisabled: { type: 'boolean' } }, ['landingDisabled'])), '403': error('Site administrator required') } },
    },
    '/site/logo': {
      get: { summary: 'Read custom logo bytes', tags: [adminTag], security: [], responses: { '200': response('PNG, JPEG, WebP, or SVG bytes'), '404': error('No custom logo') } },
      put: { summary: 'Upload custom logo', description: 'Requires site administrator. Base64-decoded content is limited to 300 KiB and to PNG, JPEG, WebP, or SVG.', tags: [adminTag], requestBody: body(object({ contentType: str({ enum: ['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml'] }), data: str({ format: 'byte', writeOnly: true }) }, ['contentType', 'data'], { additionalProperties: false }), { contentType: 'image/png', data: '[BASE64 IMAGE DATA]' }), responses: { '200': ok(object({ url: str(), updatedAt: timestamp() }, ['url', 'updatedAt'])), '400': error('Invalid logo'), '403': error('Site administrator required') } },
      delete: { summary: 'Remove custom logo', description: 'Requires site administrator.', tags: [adminTag], responses: { '200': ok(success, { success: true }), '404': error('No custom logo') } },
    },
    '/workspaces': {
      get: { summary: 'List workspace memberships', description: secured(), tags: [workspaceTag], responses: { '200': ok(array(object({}, [], { additionalProperties: true }))) } },
      post: { summary: 'Create a workspace', description: 'Requires authentication. The creator receives the protected Owner role.', tags: [workspaceTag], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }) }, ['name'], { additionalProperties: false }), { name: 'Product planning' }), responses: { '201': ok(ref('Workspace')), '403': error('Account unavailable') } },
    },
    '/workspaces/{wid}': {
      get: { summary: 'Workspace detail and authorized metadata', description: 'Requires workspace membership. Metadata arrays are permission-filtered.', tags: [workspaceTag], parameters: [wid], responses: { '200': ok(object({}, [], { additionalProperties: true })), '403': error('Workspace access denied') } },
      patch: { summary: 'Rename a workspace', description: secured('workspace:manage'), tags: [workspaceTag], parameters: [wid], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }) }, ['name'], { additionalProperties: false }), { name: 'Product operations' }), responses: { '200': ok(ref('Workspace')), '403': error('Permission denied') } },
      delete: { summary: 'Permanently delete a workspace', description: 'Requires the protected Owner role. All relational workspace contents are deleted atomically; detached storage objects enter the existing garbage-collection lifecycle.', tags: [workspaceTag], parameters: [wid], responses: { '200': ok(success, { success: true }), '403': error('Workspace owner required') } },
    },
    '/workspaces/{wid}/export': { get: { summary: 'Stream complete workspace export', description: secured('items:read'), tags: [workspaceTag], parameters: [wid], responses: { '200': response('Complete versioned JSON export; attachment metadata only, never attachment bytes or secrets', object({}, [], { additionalProperties: true })) } } },
    '/workspaces/{wid}/nodes': {
      get: { summary: 'List hierarchy nodes', description: 'Requires items:read or structure:write.', tags: [structureTag], parameters: [wid], responses: { '200': ok(array(ref('Node'))) } },
      post: { summary: 'Create a project, folder, or list', description: `${secured('structure:write')} Projects and standalone lists may use a null parent; folders and nested lists require a project or folder parent.`, tags: [structureTag], parameters: [wid], requestBody: body(ref('NodeCreate'), { name: 'Release backlog', kind: 'list', parentId: null, icon: 'checklist', color: 'orange' }), responses: { '201': ok(ref('Node')), '400': error('Invalid hierarchy placement'), '403': error('Permission denied') } },
    },
    '/workspaces/{wid}/nodes/{id}': {
      patch: { summary: 'Rename, move, or style a node', description: `${secured('structure:write')} Lists may move to workspace root; inherited statuses are materialized first. Other moves reject cycles, cross-workspace parents, incompatible inherited statuses, and hierarchy depth above 32.`, tags: [structureTag], parameters: [wid, pathId('id', 'Node ID in this workspace.')], requestBody: body(ref('NodePatch'), { name: 'Ready for review', icon: 'flag', color: 'green' }), responses: { '200': ok(ref('Node')), '400': error('Invalid node update'), '404': error('Node not found'), '409': error('Location changed; reload before moving') } },
      delete: { summary: 'Delete an empty node', description: secured('structure:write'), tags: [structureTag], parameters: [wid, pathId('id', 'Node ID in this workspace.')], responses: { '200': ok(success, { success: true }), '404': error('Node not found'), '409': error('Node must be empty before deletion') } },
    },
    '/workspaces/{wid}/items': {
      get: { summary: 'Stream all matching tasks', description: secured('items:read'), tags: [itemsTag], parameters: itemFilters, responses: { '200': response('Complete JSON task array streamed from a bounded-lifetime snapshot', array(ref('Item'))) } },
      post: { summary: 'Create a task', description: `${secured('items:write')} nodeId must be a list and status must belong to its effective workflow.`, tags: [itemsTag], parameters: [wid], requestBody: body(ref('ItemCreate'), { nodeId: '33333333-3333-4333-8333-333333333333', title: 'Prepare release notes', priority: 'high', tags: ['release'] }), responses: { '201': ok(ref('Item')), '400': error('Invalid task'), '404': error('Node or parent task not found') } },
    },
    '/workspaces/{wid}/items/page': { get: { summary: 'Cursor-paged tasks', description: secured('items:read'), tags: [itemsTag], parameters: [...itemFilters, query('limit', { type: 'integer', minimum: 1, maximum: 500, default: 200 }), query('cursor', str({ minLength: 1, maxLength: 1024 }), 'Opaque cursor bound to workspace and active filters; it is not a credential.')], responses: { '200': ok(object({ items: array(ref('Item')), nextCursor: nullable(str()) }, ['items', 'nextCursor'])), '400': error('Invalid item cursor') } } },
    '/workspaces/{wid}/items/bulk': { post: { summary: 'Archive or delete selected tasks atomically', description: 'Archive requires items:read and items:write; delete requires items:delete. Every target revision is checked and parent tasks require all subtasks in the same selection.', tags: [itemsTag], parameters: [wid], requestBody: body(object({ action: str({ enum: ['archive', 'delete'] }), items: array(object({ id: uuid(), expectedUpdatedAt: timestamp() }, ['id', 'expectedUpdatedAt'], { additionalProperties: false }), { minItems: 1, maxItems: 100, uniqueItems: true }) }, ['action', 'items'], { additionalProperties: false }), { action: 'archive', items: [{ id: '33333333-3333-4333-8333-333333333333', expectedUpdatedAt: '2026-09-08T10:00:00.000Z' }] }), responses: { '200': ok(object({ action: str({ enum: ['archive', 'delete'] }), affected: { type: 'integer', minimum: 1, maximum: 100 } }, ['action', 'affected'])), '404': error('Task not found'), '409': error('A task changed or has unselected subtasks') } } },
    '/workspaces/{wid}/items/import': { post: { summary: 'Import tasks atomically from JSON or CSV', description: `${secured('items:write')} Maximum 500 rows and 1,000,000 characters; a row failure rolls back the whole import.`, tags: [itemsTag], parameters: [wid], requestBody: body(object({ nodeId: uuid(), format: str({ enum: ['json', 'csv'] }), data: str({ maxLength: 1000000 }) }, ['nodeId', 'format', 'data'], { additionalProperties: false }), { nodeId: '33333333-3333-4333-8333-333333333333', format: 'json', data: '[{"title":"Imported task","priority":"medium"}]' }), responses: { '201': ok(object({ imported: { type: 'integer', minimum: 0, maximum: 500 }, ids: array(uuid(), { maxItems: 500 }) }, ['imported', 'ids'])), '400': error('Import validation failed') } } },
    '/workspaces/{wid}/items/export': { get: { summary: 'Export tasks as JSON or CSV', description: secured('items:read'), tags: [itemsTag], parameters: [wid, query('format', str({ enum: ['json', 'csv'], default: 'json' })), query('nodeId', uuid()), query('status', str({ maxLength: 64 })), query('search', str({ maxLength: 300 })), query('limit', { type: 'integer', minimum: 1, maximum: 5000, default: 1000 })], responses: { '200': response('Task array or CSV attachment') } } },
    '/workspaces/{wid}/items/{id}': {
      get: { summary: 'Get a task', description: secured('items:read'), tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], responses: { '200': ok(ref('Item')), '404': error('Task not found') } },
      patch: { summary: 'Update a task', description: 'Requires both items:read and items:write. Optional expectedUpdatedAt provides optimistic concurrency; omitted means last-write-wins.', tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], requestBody: body(ref('ItemPatch'), { title: 'Prepare final release notes', expectedUpdatedAt: '2026-09-08T10:00:00.000Z' }), responses: { '200': ok(ref('Item')), '400': error('Invalid task update'), '404': error('Task not found'), '409': error('Item changed; reload before saving') } },
      delete: { summary: 'Delete a task', description: secured('items:delete'), tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], responses: { '200': ok(success, { success: true }), '404': error('Task not found'), '409': error('Task has subtasks and cannot be deleted') } },
    },
    '/workspaces/{wid}/items/{id}/comments': {
      get: { summary: 'List task comments', description: secured('items:read'), tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], responses: { '200': ok(array(ref('Comment'))) } },
      post: { summary: 'Add a task comment or reply', description: 'Requires items:read and items:write. Optional parentId must identify a comment on this task and reply depth is limited to 32. User mention links are validated against active workspace readers and notify at most 20 recipients.', tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], requestBody: body(object({ body: str({ minLength: 1, maxLength: 10000 }), parentId: nullable(uuid()) }, ['body'], { additionalProperties: false }), { body: 'Please review this task.', parentId: null }), responses: { '201': ok(ref('Comment')), '400': error('Invalid comment, reply depth, or mention'), '404': error('Task or parent comment not found') } },
    },
    '/workspaces/{wid}/items/{id}/comments/{commentId}': { delete: { summary: 'Delete a comment or remove its tombstone', description: 'The author or comments:manage may replace a live comment with a tombstone. A subsequent call requires comments:manage and permanently removes that deleted entry while preserving its replies.', tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.'), pathId('commentId', 'Comment ID on this task.')], responses: { '200': ok(success, { success: true }), '403': error('Comment author or comments manager required'), '404': error('Comment not found') } } },
    '/workspaces/{wid}/items/{id}/comments/{commentId}/reaction': { patch: { summary: 'Add or remove the current member reaction', description: 'Requires items:read and items:write. Reactions are unique per member, comment, and emoji.', tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.'), pathId('commentId', 'Comment ID on this task.')], requestBody: body(object({ emoji: str({ enum: ['👍', '❤️', '😂', '🎉', '😕', '👀'] }), active: { type: 'boolean' } }, ['emoji', 'active'], { additionalProperties: false }), { emoji: '👍', active: true }), responses: { '200': ok(object({ emoji: str(), active: { type: 'boolean' }, count: { type: 'integer', minimum: 0 } }, ['emoji', 'active', 'count'])), '404': error('Comment not found'), '409': error('Deleted comments cannot receive reactions') } } },
    '/workspaces/{wid}/notifications': { get: { summary: 'List the current member notifications', description: secured('items:read'), tags: [itemsTag], parameters: [wid], responses: { '200': ok(array(ref('Notification'))) } } },
    '/workspaces/{wid}/notifications/unread-count': { get: { summary: 'Count the current member unread notifications', description: secured('items:read'), tags: [itemsTag], parameters: [wid], responses: { '200': ok(object({ unread: { type: 'integer', minimum: 0 } }, ['unread'])) } } },
    '/workspaces/{wid}/notifications/{id}': {
      patch: { summary: 'Mark an owned notification read or unread', description: secured('items:read'), tags: [itemsTag], parameters: [wid, pathId('id', 'Notification ID owned by the current member.')], requestBody: body(object({ read: { type: 'boolean' } }, ['read'], { additionalProperties: false }), { read: true }), responses: { '200': ok(object({ id: uuid(), readAt: nullable(timestamp()) }, ['id', 'readAt'])), '404': error('Notification not found') } },
      delete: { summary: 'Delete an owned notification', description: secured('items:read'), tags: [itemsTag], parameters: [wid, pathId('id', 'Notification ID owned by the current member.')], responses: { '200': ok(success, { success: true }), '404': error('Notification not found') } },
    },
    '/workspaces/{wid}/fields': {
      get: { summary: 'List workspace field definitions', description: 'Requires items:read or structure:write.', tags: [structureTag], parameters: [wid], responses: { '200': ok(array(ref('Field'))) } },
      post: { summary: 'Create a field definition', description: `${secured('structure:write')} Optional projectId identifies a root project or standalone list and creates the assignment atomically.`, tags: [structureTag], parameters: [wid], requestBody: body(ref('FieldCreate'), { name: 'Effort', type: 'rating', settings: { maxRating: 5 } }), responses: { '201': ok(ref('Field')), '400': error('Invalid field definition') } },
    },
    '/workspaces/{wid}/fields/{id}': {
      patch: { summary: 'Update a field definition', description: `${secured('structure:write')} Field type cannot change; updates that invalidate stored values or formula references are rejected.`, tags: [structureTag], parameters: [wid, pathId('id', 'Field ID in this workspace.')], requestBody: body(ref('FieldPatch'), { name: 'Delivery effort', settings: { maxRating: 5 } }), responses: { '200': ok(ref('Field')), '404': error('Field not found'), '409': error('Field update conflicts with stored values or formulas') } },
      delete: { summary: 'Delete a field and its values', description: `${secured('structure:write')} Also removes assignments and task values; referenced fields cannot be deleted.`, tags: [structureTag], parameters: [wid, pathId('id', 'Field ID in this workspace.')], responses: { '200': ok(success, { success: true }), '404': error('Field not found'), '409': error('Field is referenced by a formula') } },
    },
    '/workspaces/{wid}/projects/{projectId}/fields': {
      get: { summary: 'Read field-owner configuration', description: 'Requires items:read or structure:write. The target must be a root project or standalone root list.', tags: [structureTag], parameters: [wid, pathId('projectId', 'Root project or standalone list ID in this workspace.')], responses: { '200': ok(ref('ProjectFields')) } },
      patch: { summary: 'Update fields, workflow, or date format', description: `${secured('structure:write')} The target may be a root project or standalone list. Standalone workflows remain managed by the list-status endpoint. Optional expectedUpdatedAt protects against concurrent updates; project statuses in use cannot be removed. Null dateFormat restores the default.`, tags: [structureTag], parameters: [wid, pathId('projectId', 'Root project or standalone list ID in this workspace.')], requestBody: body(object({ fieldIds: array(uuid(), { maxItems: 100, uniqueItems: true }), builtInFields: array(str({ enum: ['priority', 'startDate', 'tags', 'description', 'nodeId', 'createdAt', 'updatedAt'] }), { maxItems: 7, uniqueItems: true }), statuses: array(ref('Status'), { minItems: 1, maxItems: 50 }), dateFormat: nullable(str({ enum: ['yyyy-MM-dd', 'MMM d, yyyy', 'MMMM d, yyyy', 'dd/MM/yyyy'] })), expectedUpdatedAt: timestamp() }, [], { additionalProperties: false, anyOf: [{ required: ['fieldIds'] }, { required: ['builtInFields'] }, { required: ['statuses'] }, { required: ['dateFormat'] }] }), { builtInFields: ['priority', 'tags'], expectedUpdatedAt: '2026-09-08T10:00:00.000Z' }), responses: { '200': ok(ref('ProjectFields')), '400': error('Invalid field-owner configuration'), '409': error('Field configuration changed or statuses remain in use') } },
    },
    '/workspaces/{wid}/views/list/settings': {
      get: { summary: "Read the authenticated member's List settings", description: secured('items:read'), tags: [itemsTag], parameters: [wid, query('projectId', uuid(), 'Root project or standalone-list field scope; omit for workspace-wide scope.')], responses: { '200': ok(ref('ListViewSettings')) } },
      patch: { summary: "Replace the authenticated member's List settings", description: `${secured('items:read')} Identity always comes from authentication. expectedUpdatedAt must be null when creating or exactly match the stored revision.`, tags: [itemsTag], parameters: [wid], requestBody: body(object({ projectId: nullable(uuid()), columnOrder: array(str({ maxLength: 43 }), { maxItems: 111, uniqueItems: true }), hiddenColumns: array(str({ maxLength: 43 }), { maxItems: 110, uniqueItems: true }), sort: listSortSchema, expectedUpdatedAt: nullable(timestamp()) }, ['columnOrder', 'hiddenColumns', 'sort', 'expectedUpdatedAt'], { additionalProperties: false }), { projectId: null, columnOrder: ['title', 'status', 'dueDate'], hiddenColumns: [], sort: { column: 'dueDate', direction: 'asc' }, expectedUpdatedAt: null }), responses: { '200': ok(ref('ListViewSettings')), '400': error('Invalid List settings'), '409': error('List view settings changed; reload before saving') } },
    },
    '/workspaces/{wid}/lists/{listId}/statuses': {
      get: { summary: 'Read a list workflow override or inheritance state', description: 'Requires items:read or structure:write. Standalone root lists always return explicit statuses and omit inheritedProjectUpdatedAt.', tags: [structureTag], parameters: [wid, pathId('listId', 'List ID in this workspace.')], responses: { '200': ok(ref('ListStatuses')) } },
      patch: { summary: 'Set or clear a list workflow override', description: `${secured('structure:write')} null restores project inheritance and is invalid for a standalone root list. Enabling an override from inheritance requires the current project revision.`, tags: [structureTag], parameters: [wid, pathId('listId', 'List ID in this workspace.')], requestBody: body(object({ statuses: nullable(array(ref('Status'), { minItems: 1, maxItems: 50 })), expectedUpdatedAt: timestamp(), expectedProjectUpdatedAt: timestamp() }, ['statuses'], { additionalProperties: false }), { statuses: null, expectedUpdatedAt: '2026-09-08T10:00:00.000Z' }), responses: { '200': ok(ref('ListStatuses')), '400': error('Invalid list workflow'), '409': error('List or project statuses changed') } },
    },
    '/workspaces/{wid}/lists/{listId}/tag-colors': {
      get: { summary: 'Read per-list tag colors', description: 'Requires items:read or structure:write.', tags: [structureTag], parameters: [wid, pathId('listId', 'List ID in this workspace.')], responses: { '200': ok(ref('ListTagColors')) } },
      patch: { summary: 'Replace per-list tag colors', description: `${secured('structure:write')} Up to 30 trimmed tag names map to six-digit hex colors. expectedUpdatedAt is mandatory.`, tags: [structureTag], parameters: [wid, pathId('listId', 'List ID in this workspace.')], requestBody: body(object({ colors: tagColorsMap, expectedUpdatedAt: timestamp() }, ['colors', 'expectedUpdatedAt'], { additionalProperties: false }), { colors: { release: '#e36b24', blocked: '#b42318' }, expectedUpdatedAt: '2026-09-08T10:00:00.000Z' }), responses: { '200': ok(ref('ListTagColors')), '400': error('Invalid tag color map'), '409': error('List tag colors changed; reload before saving') } },
    },
    '/workspaces/{wid}/members': { post: { summary: 'Add an existing active account to a workspace', description: `${secured('members:manage')} The actor cannot grant permissions they do not hold.`, tags: [workspaceTag], parameters: [wid], requestBody: body(object({ email: str({ format: 'email', maxLength: 254 }), roleId: uuid() }, ['email', 'roleId'], { additionalProperties: false }), { email: 'member@example.test', roleId: '44444444-4444-4444-8444-444444444444' }), responses: { '201': ok(ref('Membership')), '403': error('Permission denied'), '404': error('Active user not found') } } },
    '/workspaces/{wid}/members/{userId}': {
      patch: { summary: 'Change a member role', description: `${secured('members:manage')} Permission escalation and removal of the last active Owner are rejected.`, tags: [workspaceTag], parameters: [wid, pathId('userId', 'Member user ID.')], requestBody: body(object({ roleId: uuid() }, ['roleId'], { additionalProperties: false }), { roleId: '44444444-4444-4444-8444-444444444444' }), responses: { '200': ok(ref('Membership')), '404': error('Member not found'), '409': error('Workspace must retain an active Owner') } },
      delete: { summary: 'Remove a workspace member', description: `${secured('members:manage')} Clears this member's assignments and protects the last active Owner.`, tags: [workspaceTag], parameters: [wid, pathId('userId', 'Member user ID.')], responses: { '200': ok(success, { success: true }), '404': error('Member not found'), '409': error('Workspace must retain an active Owner') } },
    },
    '/workspaces/{wid}/roles': {
      get: { summary: 'List roles visible to the caller', description: 'Requires workspace membership; the catalog is permission-filtered.', tags: [workspaceTag], parameters: [wid], responses: { '200': ok(array(ref('Role'))) } },
      post: { summary: 'Create a role', description: `${secured('roles:manage')} The actor cannot grant permissions they do not hold.`, tags: [workspaceTag], parameters: [wid], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }), permissions: array(str({ enum: [...permissions] }), { maxItems: permissions.length, uniqueItems: true }) }, ['name', 'permissions'], { additionalProperties: false }), { name: 'Editor', permissions: ['items:read', 'items:write'] }), responses: { '201': ok(ref('Role')), '403': error('Permission denied') } },
    },
    '/workspaces/{wid}/roles/{id}': {
      patch: { summary: 'Update a role', description: `${secured('roles:manage')} The Owner role is protected and permission escalation is rejected.`, tags: [workspaceTag], parameters: [wid, pathId('id', 'Role ID in this workspace.')], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }), permissions: array(str({ enum: [...permissions] }), { maxItems: permissions.length, uniqueItems: true }) }, [], { additionalProperties: false }), { permissions: ['items:read', 'items:write'] }), responses: { '200': ok(ref('Role')), '403': error('Owner role is protected'), '404': error('Role not found') } },
      delete: { summary: 'Delete an unassigned role', description: `${secured('roles:manage')} The Owner role is protected.`, tags: [workspaceTag], parameters: [wid, pathId('id', 'Role ID in this workspace.')], responses: { '200': ok(success, { success: true }), '403': error('Owner role is protected'), '409': error('Role is assigned to members') } },
    },
    '/workspaces/{wid}/webhooks': {
      get: { summary: 'List webhooks', description: secured('workspace:manage'), tags: [automationsTag], parameters: [wid], responses: { '200': ok(array(ref('Webhook'))) } },
      post: { summary: 'Create a webhook', description: `${secured('workspace:manage')} Maximum 20 per workspace. The signing secret is returned once and never appears in list responses.`, tags: [automationsTag], parameters: [wid], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }), url: str({ format: 'uri', maxLength: 2000 }), events: array(event, { minItems: 1, maxItems: events.length }), enabled: { type: 'boolean', default: true } }, ['name', 'url', 'events'], { additionalProperties: false }), { name: 'Issue mirror', url: 'https://hooks.example.test/hopya', events: ['item.created'], enabled: true }), responses: { '200': ok({ allOf: [ref('Webhook'), object({ secret: str({ writeOnly: true }) }, ['secret'])] }, { id: '55555555-5555-4555-8555-555555555555', name: 'Issue mirror', url: 'https://hooks.example.test/hopya', events: ['item.created'], enabled: true, secret: '[REDACTED]', createdAt: '2026-09-08T10:00:00.000Z', updatedAt: '2026-09-08T10:00:00.000Z' }), '400': error('Invalid webhook') } },
    },
    '/workspaces/{wid}/webhooks/{id}': {
      patch: { summary: 'Update a webhook', description: secured('workspace:manage'), tags: [automationsTag], parameters: [wid, pathId('id', 'Webhook ID in this workspace.')], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }), url: str({ format: 'uri', maxLength: 2000 }), events: array(event, { minItems: 1, maxItems: events.length }), enabled: { type: 'boolean' } }, [], { additionalProperties: false }), { enabled: false }), responses: { '200': ok(ref('Webhook')), '404': error('Webhook not found') } },
      delete: { summary: 'Delete a webhook and its run history', description: secured('workspace:manage'), tags: [automationsTag], parameters: [wid, pathId('id', 'Webhook ID in this workspace.')], responses: { '200': ok(success, { success: true }), '404': error('Webhook not found') } },
    },
    '/workspaces/{wid}/webhooks/{id}/rotate': { post: { summary: 'Rotate a webhook signing secret', description: `${secured('workspace:manage')} The replacement secret is returned once.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Webhook ID in this workspace.')], responses: { '200': ok(object({ secret: str({ writeOnly: true }) }, ['secret']), { secret: '[REDACTED]' }), '404': error('Webhook not found') } } },
    '/workspaces/{wid}/automations': {
      get: { summary: 'List automations with ordered steps', description: secured('workspace:manage'), tags: [automationsTag], parameters: [wid], responses: { '200': ok(array(ref('Automation'))) } },
      post: { summary: 'Create an automation', description: `${secured('workspace:manage')} Maximum 50 per workspace. Supply exactly one legacy action or an ordered 1-20 step list; references may use only prior \`{{steps.N.output}}\` values.`, tags: [automationsTag], parameters: [wid], requestBody: body(ref('AutomationInput'), { name: 'Record and notify', event: 'item.created', steps: actionExamples, enabled: true }), responses: { '200': ok(ref('Automation')), '400': error('Invalid automation or step sequence') } },
    },
    '/workspaces/{wid}/automations/{id}': {
      patch: { summary: 'Update an automation', description: `${secured('workspace:manage')} Replacing action/steps creates a new immutable step version used by future runs.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.')], requestBody: body(ref('AutomationPatch'), { steps: [{ type: 'log', config: { message: 'Automation revision two' } }], enabled: true }), responses: { '200': ok(ref('Automation')), '400': error('Invalid automation or step sequence'), '404': error('Automation not found') } },
      delete: { summary: 'Delete an automation and its run history', description: secured('workspace:manage'), tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.')], responses: { '200': ok(success, { success: true }), '404': error('Automation not found') } },
    },
    '/workspaces/{wid}/automations/{id}/test': { post: { summary: 'Queue a test run of the current automation version', description: `${secured('workspace:manage')} The test is asynchronous and does not mutate tasks; monitor runId through the run endpoint.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.')], responses: { '200': ok(object({ ok: { type: 'boolean', const: true }, event, runId: uuid(), status: { type: 'string', const: 'pending' } }, ['ok', 'event', 'runId', 'status']), { ok: true, event: 'item.created', runId: '66666666-6666-4666-8666-666666666666', status: 'pending' }), '404': error('Automation not found') } } },
    '/workspaces/{wid}/automations/runs': { get: { summary: 'Monitor recent automation and webhook runs', description: `${secured('workspace:manage')} Returns at most 100 sanitized records; raw queued event payloads and secrets are omitted.`, tags: [automationsTag], parameters: [wid, query('limit', { type: 'integer', minimum: 1, maximum: 100, default: 20 }), query('automationId', uuid(), 'Automation ID; webhook runs are not selected by this filter.'), query('status', str({ enum: ['pending', 'running', 'delivered', 'failed'] }))], responses: { '200': ok(array(ref('AutomationRun'))), '400': error('Invalid run filter') } } },
    '/workspaces/{wid}/automations/runs/{runId}': { get: { summary: 'Read one automation or webhook run', description: `${secured('workspace:manage')} Step outputs/logs are bounded and sanitized; the raw event payload is omitted.`, tags: [automationsTag], parameters: [wid, pathId('runId', 'Run ID in this workspace.')], responses: { '200': ok(ref('AutomationRun')), '404': error('Automation run not found') } } },
    '/workspaces/{wid}/agent': { post: { summary: 'Ask the optional AI assistant', description: 'Requires both agent:use and items:read. Context is bounded to 100 recent tasks and 100 lists. The response can only propose a task; mutations require separate explicit human confirmation through task routes.', tags: [automationsTag], parameters: [wid], requestBody: body(object({ message: str({ minLength: 1, maxLength: 8000 }) }, ['message'], { additionalProperties: false }), { message: 'Summarize current release work and suggest one next task.' }), responses: { '200': ok(object({ reply: str({ minLength: 1, maxLength: 16000 }), proposal: nullable(object({ title: str({ maxLength: 300 }), description: str({ maxLength: 10000 }), nodeId: uuid(), dueDate: date, priority }, ['title'], { additionalProperties: false })) }, ['reply'])), '429': error('Assistant is busy'), '502': error('AI provider failed; no tasks were changed'), '503': error('AI assistant is disabled') } } },
    '/workspaces/{wid}/items/{id}/attachments': {
      get: { summary: 'List task attachments', description: secured('items:read'), tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], responses: { '200': ok(array(ref('Attachment'))) } },
      post: { summary: 'Upload a task attachment', description: `${secured('items:write')} Base64-decoded content is limited to 10 MiB; filenames and storage object keys are validated independently.`, tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], requestBody: body(object({ name: str({ minLength: 1, maxLength: 255 }), contentType: str({ maxLength: 127 }), data: str({ format: 'byte', writeOnly: true }) }, ['name', 'contentType', 'data'], { additionalProperties: false }), { name: 'release-notes.txt', contentType: 'text/plain', data: '[BASE64 FILE DATA]' }), responses: { '201': ok(ref('Attachment')), '400': error('Invalid attachment'), '413': error('Attachment exceeds 10 MiB'), '503': error('Attachment storage unavailable') } },
    },
    '/workspaces/{wid}/items/{id}/attachments/{attachmentId}': {
      get: { summary: 'Download an attachment', description: secured('items:read'), tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.'), pathId('attachmentId', 'Attachment ID on this task.')], responses: { '200': response('Attachment bytes with forced download disposition'), '404': error('Attachment not found'), '503': error('Attachment storage unavailable') } },
      delete: { summary: 'Delete an attachment', description: `${secured('items:delete')} Access is revoked before best-effort physical cleanup.`, tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.'), pathId('attachmentId', 'Attachment ID on this task.')], responses: { '200': ok(object({ success: { type: 'boolean', const: true }, cleanupPending: { type: 'boolean' } }, ['success', 'cleanupPending']), { success: true, cleanupPending: false }), '404': error('Attachment not found') } },
    },
  }
}

export function openApiDocument() {
  return Effect.runSync(documentEffect())
}

const documentEffect = () => Effect.sync(() => ({
  openapi: '3.1.0',
  info: {
    title: 'Hopya API', version: '1.0.0',
    description: 'Self-hosted task management API. Browser clients use HttpOnly session cookies and same-origin checks for mutations; programmatic clients use revocable bearer tokens. Workspace IDs and resource IDs never grant access by themselves.',
  },
  servers: [{ url: '/api/v1' }],
  components: {
    securitySchemes: {
      bearer: { type: 'http', scheme: 'bearer', description: 'Raw API token returned once by POST /auth/tokens.' },
      session: { type: 'apiKey', in: 'cookie', name: 'hopya_session', description: 'HttpOnly browser session; unsafe requests also require a matching Origin.' },
    },
    schemas,
  },
  security: auth,
  tags: [workspaceTag, itemsTag, structureTag, automationsTag, adminTag, 'Meta'].map((name) => ({ name })),
  paths: paths(),
  'x-hopya-permissions': permissions,
}))
