// Hand-maintained OpenAPI 3.1 description of the REST surface. The spec is
// served at /api/v1/openapi.json and rendered by the Docs page.
import { Effect } from 'effect'
import { events, providerTypes } from './automations.js'
import { permissions } from './types.js'

type Schema = Record<string, unknown>
const ref = (name: string): Schema => ({ $ref: `#/components/schemas/${name}` })
const str = (extra: Schema = {}): Schema => ({ type: 'string', ...extra })
const uuid = (): Schema => str({ format: 'uuid' })
const timestamp = (): Schema => str({ format: 'date-time' })
const nullable = (schema: Schema): Schema => ({ anyOf: [schema, { type: 'null' }] })
const array = (items: Schema, extra: Schema = {}): Schema => ({ type: 'array', items, ...extra })
const object = (properties: Record<string, Schema> = {}, required: string[] = [], extra: Schema = {}): Schema => ({
  type: 'object', properties, ...(required.length ? { required } : {}), ...extra,
})
const body = (schema: Schema, example?: unknown) => ({
  required: true,
  content: { 'application/json': { schema, ...(example === undefined ? {} : { example }) } },
})
const response = (description: string, schema?: Schema, example?: unknown) => ({
  description,
  ...(schema ? { content: { 'application/json': { schema, ...(example === undefined ? {} : { example }) } } } : {}),
})
const ok = (schema: Schema, example?: unknown) => response('Success', schema, example)
const error = (description = 'Request rejected') => response(description, ref('Error'), { error: description })
const success = ref('Success')
const pathId = (name: string, description?: string) => ({ name, in: 'path', required: true, ...(description ? { description } : {}), schema: uuid() })
const query = (name: string, schema: Schema, description?: string) => ({ name, in: 'query', required: false, ...(description ? { description } : {}), schema })
const auth = [{ bearer: [] }, { session: [] }]
const secured = (permission?: string) => permission
  ? `Requires ${permission === 'automations:manage' ? 'both workspace `automations:manage` and `items:read` permissions' : `the workspace \`${permission}\` permission`}. Workspace and resource identifiers are revalidated against the authenticated user.`
  : 'Requires an authenticated account.'

const event = str({ enum: [...events] })
const priority = str({ enum: ['none', 'low', 'medium', 'high', 'urgent'] })
const nodeIcon = nullable(str({ enum: ['diamond', 'briefcase', 'target', 'folder', 'archive', 'bookmark', 'list', 'checklist', 'calendar', 'flag'] }))
const nodeColor = nullable(str({ enum: ['slate', 'orange', 'amber', 'green', 'teal', 'blue', 'violet', 'rose'] }))
const date = nullable(str({ format: 'date', pattern: '^\\d{4}-\\d{2}-\\d{2}$' }))
const hexColor = str({ pattern: '^#[0-9a-fA-F]{6}$', example: '#2f7d32' })
const action = { oneOf: [
  object({ type: { type: 'string', const: 'webhook' }, config: object({ url: str({ format: 'uri', maxLength: 2000 }), method: str({ enum: ['POST', 'PUT', 'PATCH'], default: 'POST' }) }, ['url'], { additionalProperties: false }) }, ['type', 'config'], { additionalProperties: false }),
  object({ type: { type: 'string', const: 'email' }, config: object({ to: array(str({ format: 'email', maxLength: 254 }), { minItems: 1, maxItems: 10 }), subject: str({ minLength: 1, maxLength: 200 }) }, ['to', 'subject'], { additionalProperties: false }) }, ['type', 'config'], { additionalProperties: false }),
  object({ type: { type: 'string', const: 'http' }, config: object({ url: str({ format: 'uri', maxLength: 2000 }), method: str({ enum: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'], default: 'POST' }), headers: object({}, [], { maxProperties: 20, additionalProperties: str({ maxLength: 2000 }) }), body: str({ maxLength: 20000 }) }, ['url'], { additionalProperties: false }) }, ['type', 'config'], { additionalProperties: false }),
  object({ type: { type: 'string', const: 'log' }, config: object({ message: str({ maxLength: 2000 }) }, ['message'], { additionalProperties: false }) }, ['type', 'config'], { additionalProperties: false }),
] }
const actionExamples = [
  { type: 'log', config: { message: 'Task event received' } },
  { type: 'http', config: { url: 'https://hooks.example.test/tasks', method: 'POST', headers: { 'x-source': 'hopya' }, body: '{{event}}' } },
]
const itemInputProperties: Record<string, Schema> = {
  nodeId: uuid(), title: str({ minLength: 1, maxLength: 300 }), description: str({ maxLength: 50000, default: '' }),
  status: str({ minLength: 1, maxLength: 64 }), priority, startDate: date, dueDate: date,
  tags: array(str({ minLength: 1, maxLength: 60 }), { maxItems: 30 }), customFields: object({}, [], { maxProperties: 100, additionalProperties: { anyOf: [str({ maxLength: 10000 }), { type: 'number' }, { type: 'boolean' }, array(str({ minLength: 1, maxLength: 120 }), { maxItems: 100 }), { type: 'null' }] } }),
  assigneeId: nullable(uuid()), checklist: array(object({ id: str({ maxLength: 100 }), text: str({ maxLength: 400 }), done: { type: 'boolean' } }, ['text'], { additionalProperties: false }), { maxItems: 100 }), parentId: nullable(uuid()),
}
const listSortSchema = nullable(object({ column: str({ maxLength: 43 }), direction: str({ enum: ['asc', 'desc'] }) }, ['column', 'direction'], { additionalProperties: false }))
const tagColorsMap = object({}, [], { maxProperties: 30, additionalProperties: hexColor })
const graphNodeTypes = ['trigger', 'http', 'webhook', 'email', 'log', 'update_item', 'condition', 'switch']
const graphNodeId = str({ minLength: 1, maxLength: 100, pattern: '^[A-Za-z0-9_-]+$' })
const graphPosition = object({ x: { type: 'number', minimum: -100000, maximum: 100000 }, y: { type: 'number', minimum: -100000, maximum: 100000 } }, ['x', 'y'], { additionalProperties: false })
const graphHeaders = object({}, [], { maxProperties: 20, propertyNames: str({ maxLength: 100 }), additionalProperties: str({ maxLength: 2000 }), description: 'Public request headers only. Sensitive authentication and hop-by-hop names are rejected; use credentialId for authentication.' })
const legacyHeaderMigrationRequired = { type: 'boolean', const: true, description: 'Legacy inline header values were removed; attach a credential and delete this marker before publishing.' }
const graphRequestConfig = object({ url: str({ format: 'uri', maxLength: 2000 }), method: str({ enum: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'], default: 'POST' }), headers: graphHeaders, body: str({ maxLength: 20000 }), credentialId: uuid(), legacyHeaderMigrationRequired }, ['url'], { additionalProperties: false })
const graphNode = (type: string, config: Schema) => object({ id: graphNodeId, type: { type: 'string', const: type }, position: graphPosition, config }, ['id', 'type', 'position', 'config'], { additionalProperties: false })
const graph = object({ nodes: array(ref('GraphNode'), { maxItems: 50 }), edges: array(ref('GraphEdge'), { maxItems: 75 }) }, ['nodes', 'edges'], { additionalProperties: false, description: 'A bounded directed acyclic graph with exactly one trigger. Control-flow branches are exclusive; parallel fan-out, loops, unreachable nodes, and unsafe or non-upstream output references are rejected. Execution rechecks the recorded publisher\'s current workspace membership and items:read before execution and before every node. update_item additionally rechecks items:read and items:write immediately before mutating only the triggering task.' })
const credentialTypes = ['bearer', 'api_key', 'basic', 'custom_headers', 'oauth2']
const credentialHeaderName = '^[!#$%&\'*+.^_`|~0-9A-Za-z-]+$'
const credentialSecrets: Record<string, Schema> = {
  bearer: object({ token: str({ minLength: 1, maxLength: 8192, writeOnly: true }) }, ['token'], { additionalProperties: false, title: 'Bearer secret' }),
  api_key: object({ name: str({ minLength: 1, maxLength: 100, pattern: credentialHeaderName }), value: str({ minLength: 1, maxLength: 8192, writeOnly: true }) }, ['name', 'value'], { additionalProperties: false, title: 'API key header secret' }),
  basic: object({ username: str({ maxLength: 1000, writeOnly: true }), password: str({ maxLength: 8192, writeOnly: true }) }, ['username', 'password'], { additionalProperties: false, title: 'Basic authentication secret' }),
  custom_headers: object({ headers: object({}, [], { maxProperties: 20, propertyNames: str({ minLength: 1, maxLength: 100, pattern: credentialHeaderName }), additionalProperties: str({ maxLength: 2000 }), writeOnly: true }) }, ['headers'], { additionalProperties: false, title: 'Custom header secrets' }),
  oauth2: object({
    authorizationUrl: str({ format: 'uri', maxLength: 2000 }), tokenUrl: str({ format: 'uri', maxLength: 2000 }), clientId: str({ minLength: 1, maxLength: 1000 }),
    clientSecret: str({ maxLength: 8192, writeOnly: true }), scopes: array(str({ minLength: 1, maxLength: 200 }), { maxItems: 30, default: [] }),
    accessToken: str({ maxLength: 8192, writeOnly: true }), refreshToken: str({ maxLength: 8192, writeOnly: true }), expiresAt: timestamp(),
  }, ['authorizationUrl', 'tokenUrl', 'clientId'], { additionalProperties: false, title: 'OAuth 2.0 authorization-code secret and provider settings' }),
}
const credentialSecret = {
  oneOf: Object.values(credentialSecrets),
  writeOnly: true,
}
const credentialCreate = (type: string) => object({ name: str({ minLength: 1, maxLength: 120 }), type: { type: 'string', const: type }, origin: str({ format: 'uri', maxLength: 2000 }), pathPrefix: nullable(str({ maxLength: 1000, default: null })), secret: { ...credentialSecrets[type]!, writeOnly: true } }, ['name', 'type', 'origin', 'secret'], { additionalProperties: false })

const schemas = {
  Error: object({ error: str() }, ['error'], { additionalProperties: false }),
  Success: object({ success: { type: 'boolean', const: true } }, ['success'], { additionalProperties: false }),
  User: object({ id: uuid(), name: str({ maxLength: 120 }), email: str({ format: 'email' }), isAdmin: { type: 'boolean' } }, ['id', 'name', 'email', 'isAdmin']),
  AdminUser: object({ id: uuid(), name: str(), email: str({ format: 'email' }), isAdmin: { type: 'boolean' }, disabled: { type: 'boolean' }, createdAt: timestamp() }, ['id', 'name', 'email', 'isAdmin', 'disabled', 'createdAt']),
  Workspace: object({ id: uuid(), name: str({ maxLength: 120 }), createdAt: timestamp() }, ['id', 'name', 'createdAt']),
  ChecklistEntry: object({ id: uuid(), text: str({ maxLength: 200 }), done: { type: 'boolean' } }, ['id', 'text', 'done']),
  Item: object({
    id: uuid(), workspaceId: uuid(), nodeId: uuid(), title: str({ maxLength: 300 }), description: str({ maxLength: 50000 }),
    status: str({ minLength: 1, maxLength: 64 }), priority, startDate: date, dueDate: date,
    tags: array(str({ maxLength: 60 }), { maxItems: 30 }), customFields: object({}, [], { additionalProperties: true }),
    assigneeId: nullable(uuid()), checklist: array(ref('ChecklistEntry'), { maxItems: 100 }), parentId: nullable(uuid()), bodyRevision: { type: 'integer', minimum: 1 }, archivedAt: nullable(timestamp()),
    createdAt: timestamp(), updatedAt: timestamp(),
  }, ['id', 'workspaceId', 'nodeId', 'title', 'description', 'status', 'priority', 'startDate', 'dueDate', 'tags', 'customFields', 'assigneeId', 'checklist', 'parentId', 'bodyRevision', 'archivedAt', 'createdAt', 'updatedAt']),
  ItemCreate: object(itemInputProperties, ['nodeId', 'title'], { additionalProperties: false }),
  ItemPatch: object({ ...itemInputProperties, expectedUpdatedAt: timestamp() }, [], { additionalProperties: false }),
  Node: object({
    id: uuid(), workspaceId: uuid(), name: str({ maxLength: 120 }), description: str({ maxLength: 50000 }),
    kind: str({ enum: ['project', 'folder', 'list'] }), parentId: nullable(uuid()), icon: nodeIcon, color: nodeColor, createdAt: timestamp(),
  }, ['id', 'workspaceId', 'name', 'description', 'kind', 'parentId', 'icon', 'color', 'createdAt']),
  NodeCreate: object({ name: str({ minLength: 1, maxLength: 120 }), description: str({ maxLength: 50000 }), kind: str({ enum: ['project', 'folder', 'list'] }), parentId: nullable(uuid()), icon: nodeIcon, color: nodeColor }, ['name', 'kind'], { additionalProperties: false }),
  NodePatch: object({ name: str({ minLength: 1, maxLength: 120 }), description: str({ maxLength: 50000 }), parentId: nullable(uuid()), expectedParentId: nullable(uuid()), icon: nodeIcon, color: nodeColor }, [], { additionalProperties: false, anyOf: [{ required: ['name'] }, { required: ['description'] }, { required: ['parentId'] }, { required: ['icon'] }, { required: ['color'] }], dependentRequired: { expectedParentId: ['parentId'] } }),
  FieldSettings: object({ dateFormat: str({ enum: ['yyyy-MM-dd', 'MMM d, yyyy', 'MMMM d, yyyy', 'dd/MM/yyyy'] }), maxRating: { type: 'integer', minimum: 1, maximum: 10 }, formula: str({ minLength: 1, maxLength: 200 }) }, [], { additionalProperties: false }),
  Field: object({ id: uuid(), workspaceId: uuid(), name: str({ maxLength: 120 }), type: str({ enum: ['text', 'number', 'date', 'datetime', 'checkbox', 'select', 'checklist', 'rating', 'formula'] }), options: array(str({ maxLength: 120 }), { maxItems: 100 }), settings: ref('FieldSettings') }, ['id', 'workspaceId', 'name', 'type', 'options']),
  FieldCreate: object({ name: str({ minLength: 1, maxLength: 120 }), type: str({ enum: ['text', 'number', 'date', 'datetime', 'checkbox', 'select', 'checklist', 'rating', 'formula'] }), options: array(str({ minLength: 1, maxLength: 120 }), { maxItems: 100 }), settings: ref('FieldSettings'), projectId: uuid() }, ['name', 'type'], { additionalProperties: false }),
  FieldPatch: object({ name: str({ minLength: 1, maxLength: 120 }), options: array(str({ minLength: 1, maxLength: 120 }), { maxItems: 100 }), settings: ref('FieldSettings') }, [], { additionalProperties: false, minProperties: 1 }),
  Status: object({ id: str({ minLength: 1, maxLength: 64, pattern: '^[A-Za-z0-9][A-Za-z0-9_-]*$' }), name: str({ minLength: 1, maxLength: 120 }), color: hexColor, completed: { type: 'boolean' } }, ['id', 'name', 'color', 'completed'], { additionalProperties: false }),
  ProjectFields: object({ projectId: uuid(), fieldIds: array(uuid(), { maxItems: 100, uniqueItems: true }), builtInFields: array(str({ enum: ['priority', 'startDate', 'tags', 'description', 'nodeId', 'createdAt', 'updatedAt'] }), { maxItems: 7, uniqueItems: true }), statuses: array(ref('Status'), { minItems: 1, maxItems: 50 }), dateFormat: str({ enum: ['yyyy-MM-dd', 'MMM d, yyyy', 'MMMM d, yyyy', 'dd/MM/yyyy'] }), updatedAt: timestamp() }, ['projectId', 'fieldIds', 'builtInFields', 'statuses', 'updatedAt']),
  ListStatuses: object({ listId: uuid(), statuses: array(ref('Status'), { minItems: 1, maxItems: 50 }), updatedAt: timestamp(), inheritedProjectUpdatedAt: timestamp() }, ['listId', 'updatedAt']),
  ListTagColors: object({ listId: uuid(), colors: tagColorsMap, updatedAt: timestamp() }, ['listId', 'colors', 'updatedAt']),
  ListViewSettings: object({ view: { type: 'string', const: 'list' }, projectId: nullable(uuid()), columnOrder: array(str({ maxLength: 43 }), { maxItems: 111, uniqueItems: true }), hiddenColumns: array(str({ maxLength: 43 }), { maxItems: 110, uniqueItems: true }), sort: listSortSchema, updatedAt: nullable(timestamp()) }, ['view', 'projectId', 'columnOrder', 'hiddenColumns', 'sort', 'updatedAt']),
  Role: object({ id: uuid(), workspaceId: uuid(), name: str({ maxLength: 120 }), permissions: array(str({ enum: [...permissions] }), { uniqueItems: true }), isOwner: { type: 'boolean' } }, ['id', 'workspaceId', 'name', 'permissions', 'isOwner']),
  Membership: object({ userId: uuid(), workspaceId: uuid(), roleId: uuid() }, ['userId', 'workspaceId', 'roleId']),
  Attachment: object({ id: uuid(), name: str({ maxLength: 255 }), size: { type: 'integer', minimum: 0 }, contentType: str({ maxLength: 127 }), createdAt: timestamp() }, ['id', 'name', 'size', 'contentType', 'createdAt']),
  CommentReaction: object({ emoji: str({ enum: ['👍', '❤️', '😂', '🎉', '😕', '👀'] }), count: { type: 'integer', minimum: 1 }, reactedByMe: { type: 'boolean' } }, ['emoji', 'count', 'reactedByMe']),
  CommentAnchor: object({ revision: { type: 'integer', minimum: 1 }, start: { type: 'integer', minimum: 0 }, end: { type: 'integer', minimum: 1 }, exact: str({ minLength: 1, maxLength: 2000 }), prefix: str({ maxLength: 200 }), suffix: str({ maxLength: 200 }), state: str({ enum: ['attached', 'orphaned'] }) }, ['revision', 'start', 'end', 'exact', 'prefix', 'suffix', 'state'], { additionalProperties: false }),
  CommentAnchorInput: object({ revision: { type: 'integer', minimum: 1 }, start: { type: 'integer', minimum: 0 }, end: { type: 'integer', minimum: 1 }, exact: str({ minLength: 1, maxLength: 2000 }), prefix: str({ maxLength: 200 }), suffix: str({ maxLength: 200 }) }, ['revision', 'start', 'end', 'exact'], { additionalProperties: false }),
  Comment: object({ id: uuid(), workspaceId: uuid(), itemId: uuid(), documentId: uuid(), authorId: nullable(uuid()), authorName: str({ maxLength: 120 }), body: str({ maxLength: 10000 }), parentId: nullable(uuid()), anchor: nullable(ref('CommentAnchor')), reactions: array(ref('CommentReaction'), { maxItems: 6 }), createdAt: timestamp(), deletedAt: nullable(timestamp()) }, ['id', 'workspaceId', 'authorId', 'authorName', 'body', 'parentId', 'anchor', 'reactions', 'createdAt', 'deletedAt']),
  Document: object({ id: uuid(), workspaceId: uuid(), parentId: nullable(uuid()), title: str({ minLength: 1, maxLength: 300 }), body: str({ maxLength: 50000 }), bodyRevision: { type: 'integer', minimum: 1 }, createdAt: timestamp(), updatedAt: timestamp(), createdByName: nullable(str()), updatedByName: nullable(str()) }, ['id', 'workspaceId', 'parentId', 'title', 'body', 'bodyRevision', 'createdAt', 'updatedAt', 'createdByName', 'updatedByName']),
  Notification: object({ id: uuid(), workspaceId: uuid(), type: str({ enum: ['assignment', 'mention'] }), itemId: uuid(), itemTitle: str({ maxLength: 300 }), commentId: nullable(uuid()), actorId: nullable(uuid()), actorName: str({ maxLength: 120 }), createdAt: timestamp(), readAt: nullable(timestamp()) }, ['id', 'workspaceId', 'type', 'itemId', 'itemTitle', 'commentId', 'actorId', 'actorName', 'createdAt', 'readAt']),
  Webhook: object({ id: uuid(), name: str({ maxLength: 120 }), url: str({ format: 'uri', maxLength: 2000 }), events: array(event, { minItems: 1, maxItems: events.length }), enabled: { type: 'boolean' }, signingVersion: { type: 'integer', enum: [1, 2], description: '1 retains the legacy SHA-256(secret + "." + body) digest until rotation; 2 uses HMAC-SHA256 over the exact body. Both versions reject all 3xx responses. Redirect-dependent integrations must use the final endpoint URL: this intentional security-hardening compatibility break prevents forwarding payloads or secrets beyond the checked destination.' }, createdAt: timestamp(), updatedAt: timestamp() }, ['id', 'name', 'url', 'events', 'enabled', 'signingVersion', 'createdAt', 'updatedAt']),
  Action: { ...action, examples: actionExamples },
  Automation: {
    oneOf: [
      object({ id: uuid(), workspaceId: uuid(), name: str({ maxLength: 120 }), event, version: { type: 'integer', minimum: 1 }, enabled: { type: 'boolean' }, steps: array(ref('Action'), { minItems: 1, maxItems: 20 }), action: ref('Action'), createdAt: timestamp(), updatedAt: timestamp() }, ['id', 'workspaceId', 'name', 'event', 'version', 'enabled', 'steps', 'createdAt', 'updatedAt'], { title: 'Legacy linear automation' }),
      object({ id: uuid(), workspaceId: uuid(), name: str({ maxLength: 120 }), event, version: { type: 'integer', minimum: 1 }, enabled: { type: 'boolean' }, graph: { type: 'boolean', const: true }, createdAt: timestamp(), updatedAt: timestamp() }, ['id', 'workspaceId', 'name', 'event', 'version', 'enabled', 'graph', 'createdAt', 'updatedAt'], { additionalProperties: false, title: 'Published graph automation' }),
    ],
    description: 'Current automation metadata. Linear versions include steps and retain the single-action compatibility alias; graph versions expose graph=true and are read through draft/version routes. Both linear and graph outbound requests reject all 3xx responses; legacy redirect behavior is intentionally not retained. Use final endpoint URLs.',
  },
  AutomationInput: object({ name: str({ minLength: 1, maxLength: 120 }), event, action: ref('Action'), steps: array(ref('Action'), { minItems: 1, maxItems: 20 }), enabled: { type: 'boolean', default: true } }, ['name', 'event'], { additionalProperties: false, oneOf: [{ required: ['action'], not: { required: ['steps'] } }, { required: ['steps'], not: { required: ['action'] } }] }),
  AutomationPatch: object({ name: str({ minLength: 1, maxLength: 120 }), event, action: ref('Action'), steps: array(ref('Action'), { minItems: 1, maxItems: 20 }), enabled: { type: 'boolean' } }, [], { additionalProperties: false, not: { required: ['action', 'steps'] } }),
  GraphNode: {
    oneOf: [
      graphNode('trigger', object({ event }, ['event'], { additionalProperties: false })),
      graphNode('http', graphRequestConfig),
      graphNode('webhook', object({ url: str({ format: 'uri', maxLength: 2000 }), method: str({ enum: ['POST', 'PUT', 'PATCH'], default: 'POST' }), headers: graphHeaders, body: str({ maxLength: 20000 }), credentialId: uuid(), legacyHeaderMigrationRequired }, ['url'], { additionalProperties: false })),
      graphNode('email', object({ to: array(str({ format: 'email', maxLength: 254 }), { minItems: 1, maxItems: 10 }), subject: str({ minLength: 1, maxLength: 200 }) }, ['to', 'subject'], { additionalProperties: false })),
      graphNode('log', object({ message: str({ maxLength: 2000 }) }, ['message'], { additionalProperties: false })),
      graphNode('update_item', object({ patch: object({ title: str({ minLength: 1, maxLength: 300 }), description: str({ maxLength: 50000 }), status: str({ minLength: 1, maxLength: 64 }), priority, startDate: nullable(str({ maxLength: 64 })), dueDate: nullable(str({ maxLength: 64 })), assigneeId: nullable(uuid()), tags: array(str({ minLength: 1, maxLength: 60 }), { maxItems: 30 }) }, [], { additionalProperties: false, minProperties: 1 }) }, ['patch'], { additionalProperties: false })),
      graphNode('condition', object({ path: str({ minLength: 1, maxLength: 200 }), operator: str({ enum: ['equals', 'not_equals', 'exists', 'contains'] }), value: {} }, ['path', 'operator'], { additionalProperties: false })),
      graphNode('switch', object({ path: str({ minLength: 1, maxLength: 200 }), cases: array(object({ branch: str({ minLength: 1, maxLength: 100 }), value: { type: ['string', 'number', 'boolean', 'null'] } }, ['branch', 'value'], { additionalProperties: false }), { minItems: 1, maxItems: 20 }), defaultBranch: str({ minLength: 1, maxLength: 100 }) }, ['path', 'cases', 'defaultBranch'], { additionalProperties: false })),
    ],
  },
  GraphEdge: object({ id: graphNodeId, source: graphNodeId, target: graphNodeId, branch: str({ minLength: 1, maxLength: 100 }) }, ['id', 'source', 'target'], { additionalProperties: false }),
  AutomationGraph: graph,
  GraphValidation: object({ valid: { type: 'boolean' }, errors: array(str()) }, ['valid', 'errors'], { additionalProperties: false }),
  AutomationDraft: object({ revision: { type: 'integer', minimum: 0 }, graph: ref('AutomationGraph'), updatedAt: nullable(timestamp()) }, ['revision', 'graph', 'updatedAt'], { additionalProperties: false }),
  AutomationDraftSaved: object({ revision: { type: 'integer', minimum: 1 }, graph: ref('AutomationGraph'), updatedAt: timestamp(), validation: ref('GraphValidation') }, ['revision', 'graph', 'updatedAt', 'validation'], { additionalProperties: false }),
  AutomationVersionSummary: object({ version: { type: 'integer', minimum: 1 }, format: str({ enum: ['linear', 'graph'] }), publisherId: nullable(uuid()), publishedAt: timestamp() }, ['version', 'format', 'publisherId', 'publishedAt'], { additionalProperties: false }),
  AutomationVersion: object({ version: { type: 'integer', minimum: 1 }, format: str({ enum: ['linear', 'graph'] }), graph: ref('AutomationGraph'), publisherId: nullable(uuid()), publishedAt: timestamp() }, ['version', 'format', 'graph', 'publisherId', 'publishedAt'], { additionalProperties: false }),
  AutomationCatalog: object({
    limits: object({ maxNodes: { type: 'integer', const: 50 }, maxEdges: { type: 'integer', const: 75 }, maxGraphBytes: { type: 'integer', const: 262144 }, maxNodeConfigBytes: { type: 'integer', const: 32768 }, maxExecutionNodes: { type: 'integer', const: 50 } }, ['maxNodes', 'maxEdges', 'maxGraphBytes', 'maxNodeConfigBytes', 'maxExecutionNodes'], { additionalProperties: false }),
    events: array(object({ type: event, output: object({}, [], { additionalProperties: true }) }, ['type', 'output'], { additionalProperties: false })),
    nodes: array(object({ type: str({ enum: graphNodeTypes }), kind: str({ enum: ['trigger', 'action', 'control'] }), inputs: object({}, [], { additionalProperties: true }), outputs: object({}, [], { additionalProperties: true }), config: object({}, [], { additionalProperties: true }) }, ['type', 'kind', 'inputs', 'outputs', 'config'], { additionalProperties: false })),
  }, ['limits', 'events', 'nodes'], { additionalProperties: false }),
  GraphPreview: object({ valid: { type: 'boolean' }, errors: array(str()), uncertain: { type: 'boolean' }, path: array(object({ nodeId: graphNodeId, type: str({ enum: graphNodeTypes }), branch: str({ minLength: 1, maxLength: 100 }), effect: { type: 'string', const: 'none' }, output: {}, uncertain: { type: 'boolean' }, candidateBranches: array(str({ minLength: 1, maxLength: 100 })) }, ['nodeId', 'type', 'effect'], { additionalProperties: false }), { maxItems: 50 }) }, ['valid', 'errors', 'path'], { additionalProperties: false }),
  AutomationCredential: object({ id: uuid(), name: str({ maxLength: 120 }), type: str({ enum: credentialTypes }), origin: str({ format: 'uri', maxLength: 2000 }), pathPrefix: nullable(str({ maxLength: 1000 })), version: { type: 'integer', minimum: 1 }, status: str({ enum: ['active', 'revoked'] }), createdAt: timestamp(), updatedAt: timestamp() }, ['id', 'name', 'type', 'origin', 'pathPrefix', 'version', 'status', 'createdAt', 'updatedAt'], { additionalProperties: false, description: 'Write-only credential material is never returned.' }),
  AutomationCredentialCreate: { oneOf: credentialTypes.map(credentialCreate) },
  AutomationCredentialReplace: object({ expectedVersion: { type: 'integer', minimum: 1 }, name: str({ minLength: 1, maxLength: 120 }), secret: credentialSecret }, ['expectedVersion', 'secret'], { additionalProperties: false }),
  StepRun: object({ id: uuid(), stepId: uuid(), position: { type: 'integer', minimum: 1 }, type: str({ enum: [...providerTypes] }), status: str({ enum: ['pending', 'running', 'delivered', 'failed', 'skipped'] }), output: str({ maxLength: 8192 }), log: str({ maxLength: 2000 }), startedAt: nullable(timestamp()), completedAt: nullable(timestamp()) }, ['id', 'stepId', 'position', 'type', 'status', 'output', 'log', 'startedAt', 'completedAt']),
  NodeRun: object({ id: uuid(), nodeId: graphNodeId, type: str({ enum: graphNodeTypes }), status: str({ enum: ['pending', 'running', 'delivered', 'failed', 'skipped'] }), attempt: { type: 'integer', minimum: 0 }, output: str({ maxLength: 8192 }), log: str({ maxLength: 2000 }), startedAt: nullable(timestamp()), completedAt: nullable(timestamp()) }, ['id', 'nodeId', 'type', 'status', 'attempt', 'output', 'log', 'startedAt', 'completedAt'], { additionalProperties: false }),
  AutomationRun: object({ id: uuid(), workspaceId: uuid(), automationId: nullable(uuid()), targetType: str({ enum: ['automation', 'webhook'] }), targetId: uuid(), automationVersion: nullable({ type: 'integer', minimum: 1 }), status: str({ enum: ['pending', 'running', 'delivered', 'failed'] }), detail: str({ maxLength: 2000 }), createdAt: timestamp(), startedAt: nullable(timestamp()), completedAt: nullable(timestamp()), heartbeatAt: nullable(timestamp()), attempt: { type: 'integer', minimum: 0 }, steps: array(ref('StepRun'), { maxItems: 20 }), nodes: array(ref('NodeRun'), { maxItems: 50 }) }, ['id', 'workspaceId', 'automationId', 'targetType', 'targetId', 'automationVersion', 'status', 'detail', 'createdAt', 'startedAt', 'completedAt', 'heartbeatAt', 'attempt', 'steps', 'nodes']),
  OidcIdentity: object({ id: uuid(), userId: uuid(), issuer: str({ format: 'uri', maxLength: 2048 }), subject: str({ minLength: 1, maxLength: 255 }), createdAt: timestamp() }, ['id', 'userId', 'issuer', 'subject', 'createdAt']),
}

const workspaceTag = 'Workspaces'
const itemsTag = 'Tasks'
const documentsTag = 'Documents'
const structureTag = 'Structure & fields'
const automationsTag = 'Automations'
const adminTag = 'Accounts & admin'

function paths() {
  const wid = pathId('wid', 'Workspace ID; membership and the operation permission are checked server-side.')
  const version = { name: 'version', in: 'path', required: true, description: 'Positive immutable automation version.', schema: { type: 'integer', minimum: 1 } }
  const itemFilters = [wid, query('nodeId', uuid(), 'Exact list ID.'), query('search', str({ maxLength: 300 }), 'Title/description search.'), query('status', str({ maxLength: 64 }), 'Exact effective status ID.'), query('archived', str({ enum: ['exclude', 'include', 'only'], default: 'exclude' }), 'Archived-task visibility.')]
  return {
    '/health': { get: { summary: 'Health probe', tags: ['Meta'], security: [], servers: [{ url: '/' }], responses: { '200': ok(object({ status: { type: 'string', const: 'ok' } }, ['status']), { status: 'ok' }) } } },
    '/config': { get: { summary: 'Public instance configuration', tags: ['Meta'], security: [], responses: { '200': ok(object({ landingEnabled: { type: 'boolean' }, logo: str(), registrationEnabled: { type: 'boolean' }, setupRequired: { type: 'boolean' }, ssoEnabled: { type: 'boolean' }, aiEnabled: { type: 'boolean' }, passwordResetEnabled: { type: 'boolean' } }, ['landingEnabled', 'registrationEnabled', 'setupRequired', 'ssoEnabled', 'aiEnabled', 'passwordResetEnabled'])) } } },
    '/openapi.json': { get: { summary: 'This OpenAPI 3.1 document', tags: ['Meta'], security: [], responses: { '200': response('OpenAPI JSON document', object()) } } },
    '/auth/setup': { post: { summary: 'Create the first site administrator', description: 'Public only while setup is incomplete. Requires the operator-provided setup token and creates an HttpOnly session.', tags: [adminTag], security: [], requestBody: body(object({ name: str({ maxLength: 120 }), email: str({ format: 'email', maxLength: 254 }), password: str({ minLength: 12, maxLength: 256, writeOnly: true }), setupToken: str({ maxLength: 512, writeOnly: true }) }, ['name', 'email', 'password', 'setupToken'], { additionalProperties: false }), { name: 'Administrator', email: 'admin@example.test', password: '[REDACTED]', setupToken: '[REDACTED]' }), responses: { '201': ok(ref('User')), '403': error('Setup not authorized'), '409': error('Setup already completed') } } },
    '/auth/register': { post: { summary: 'Register an account', description: 'Public only when registration is enabled and setup is complete. Creates an HttpOnly session.', tags: [adminTag], security: [], requestBody: body(object({ name: str({ maxLength: 120 }), email: str({ format: 'email', maxLength: 254 }), password: str({ minLength: 12, maxLength: 256, writeOnly: true }) }, ['name', 'email', 'password'], { additionalProperties: false }), { name: 'Example User', email: 'user@example.test', password: '[REDACTED]' }), responses: { '201': ok(ref('User')), '403': error('Registration is closed') } } },
    '/auth/login': { post: { summary: 'Password sign-in', tags: [adminTag], security: [], requestBody: body(object({ email: str({ format: 'email', maxLength: 254 }), password: str({ minLength: 1, maxLength: 256, writeOnly: true }) }, ['email', 'password'], { additionalProperties: false }), { email: 'user@example.test', password: '[REDACTED]' }), responses: { '200': ok(ref('User')), '401': error('Invalid email or password') } } },
    '/auth/forgot-password': { post: { summary: 'Request local password recovery', description: 'Always returns the same accepted response for valid email syntax. Delivery is available only when SMTP_URL and SMTP_FROM are configured.', tags: [adminTag], security: [], requestBody: body(object({ email: str({ format: 'email', maxLength: 254 }) }, ['email'], { additionalProperties: false }), { email: 'user@example.test' }), responses: { '202': ok(object({ message: str() }, ['message'])), '429': error('Too many authentication attempts') } } },
    '/auth/reset-password': { post: { summary: 'Complete local password recovery', description: 'Consumes a single-use 30-minute token and revokes all sessions and personal access tokens.', tags: [adminTag], security: [], requestBody: body(object({ token: str({ minLength: 43, maxLength: 43, writeOnly: true }), password: str({ minLength: 12, maxLength: 256, writeOnly: true }) }, ['token', 'password'], { additionalProperties: false }), { token: '[REDACTED]', password: '[REDACTED]' }), responses: { '200': ok(object({ success: { type: 'boolean' } }, ['success'])), '400': error('Password reset link is invalid or expired'), '429': error('Too many authentication attempts') } } },
    '/auth/sso': { get: { summary: 'Start an optional OIDC sign-in', description: 'Creates a short-lived HttpOnly PKCE flow cookie and redirects to the operator-configured issuer. No local account is selected by unverified email.', tags: [adminTag], security: [], responses: { '302': response('Redirect to the configured OIDC authorization endpoint'), '429': error('Too many SSO attempts'), '503': error('SSO is not configured') } } },
    '/auth/sso/callback': { get: { summary: 'Complete an optional OIDC sign-in', description: 'Validates and consumes the PKCE flow, then binds the verified issuer/subject identity. Auto-provisioning is separate and disabled by default.', tags: [adminTag], security: [], parameters: [query('code', str()), query('state', str({ maxLength: 256 })), query('error', str())], responses: { '302': response('Redirect to the authenticated application'), '401': error('SSO authentication failed'), '403': error('SSO identity is not linked to an account'), '409': error('SSO account requires administrator linking'), '503': error('SSO is not configured') } } },
    '/auth/logout': { post: { summary: 'Sign out and revoke the current session', description: secured(), tags: [adminTag], responses: { '200': ok(success, { success: true }), '401': error('Authentication required') } } },
    '/auth/me': { get: { summary: 'Current user', description: secured(), tags: [adminTag], responses: { '200': ok(ref('User')), '401': error('Authentication required') } } },
    '/auth/profile': { patch: { summary: 'Update profile or credentials', description: 'Requires authentication. Email and password changes require currentPassword and revoke other sessions and tokens.', tags: [adminTag], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }), email: str({ format: 'email', maxLength: 254 }), password: str({ minLength: 12, maxLength: 256, writeOnly: true }), currentPassword: str({ minLength: 1, maxLength: 256, writeOnly: true }) }, ['name'], { additionalProperties: false }), { name: 'Example User', email: 'user@example.test' }), responses: { '200': ok(ref('User')), '400': error('Invalid profile update'), '403': error('Current password is incorrect'), '409': error('Account changed or email is unavailable') } } },
    '/auth/tokens': {
      get: { summary: 'List API token metadata', description: secured(), tags: [adminTag], responses: { '200': ok(array(object({ id: uuid(), name: str(), createdAt: timestamp(), expiresAt: timestamp() }, ['id', 'name', 'createdAt', 'expiresAt']))) } },
      post: { summary: 'Create an API token', description: 'Requires authentication. The raw token is returned once and only its hash is stored.', tags: [adminTag], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }) }, ['name'], { additionalProperties: false }), { name: 'CLI on workstation' }), responses: { '201': ok(object({ token: str({ writeOnly: true }) }, ['token']), { token: '[REDACTED]' }), '409': error('Maximum active tokens reached') } },
    },
    '/auth/tokens/{id}': { delete: { summary: 'Revoke an API token', description: secured(), tags: [adminTag], parameters: [pathId('id', 'Token ID owned by the current account.')], responses: { '200': ok(success, { success: true }), '404': error('Token not found') } } },
    '/admin/users': {
      get: { summary: 'List accounts', description: 'Requires site administrator.', tags: [adminTag], responses: { '200': ok(array(ref('AdminUser'))), '403': error('Site administrator required') } },
      post: { summary: 'Create an account', description: 'Requires site administrator.', tags: [adminTag], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }), email: str({ format: 'email', maxLength: 254 }), password: str({ minLength: 12, maxLength: 256, writeOnly: true }), isAdmin: { type: 'boolean', default: false } }, ['name', 'email', 'password'], { additionalProperties: false }), { name: 'Example User', email: 'user@example.test', password: '[REDACTED]', isAdmin: false }), responses: { '201': ok(ref('AdminUser')), '403': error('Site administrator required') } },
    },
    '/admin/users/{id}': { patch: { summary: 'Change account admin or disabled flags', description: 'Requires site administrator. Disabling revokes credentials and clears task assignments; the last active administrator is protected.', tags: [adminTag], parameters: [pathId('id', 'Target user ID.')], requestBody: body(object({ isAdmin: { type: 'boolean' }, disabled: { type: 'boolean' } }, [], { additionalProperties: false, minProperties: 1 }), { disabled: true }), responses: { '200': ok(ref('AdminUser')), '404': error('User not found'), '409': error('Site must retain an active administrator') } } },
    '/admin/audit': { get: { summary: 'Audit log', description: 'Requires site administrator. Audit details are sanitized and do not include raw secrets or full AI prompts.', tags: [adminTag], parameters: [query('workspaceId', uuid()), query('limit', { type: 'integer', minimum: 1, maximum: 200, default: 50 }), query('offset', { type: 'integer', minimum: 0, maximum: 1000000, default: 0 })], responses: { '200': ok(array(object({}, [], { additionalProperties: true }))) } } },
    '/admin/status': { get: { summary: 'Instance status', description: 'Requires site administrator.', tags: [adminTag], responses: { '200': ok(object({}, [], { additionalProperties: true })) } } },
    '/admin/oidc-identities': {
      get: { summary: 'List linked OIDC identities', description: 'Requires site administrator. Returns issuer and subject binding metadata, never provider tokens.', tags: [adminTag], parameters: [query('userId', uuid(), 'Optional exact user filter.')], responses: { '200': ok(array(ref('OidcIdentity'))), '403': error('Site administrator required') } },
      post: { summary: 'Link an OIDC identity to an active account', description: 'Requires site administrator. Identity ownership is bound to exact issuer and subject, not email.', tags: [adminTag], requestBody: body(object({ userId: uuid(), issuer: str({ format: 'uri', minLength: 1, maxLength: 2048 }), subject: str({ minLength: 1, maxLength: 255 }) }, ['userId', 'issuer', 'subject'], { additionalProperties: false }), { userId: '11111111-1111-4111-8111-111111111111', issuer: 'https://id.example.test', subject: 'provider-subject-123' }), responses: { '201': ok(object({ id: uuid(), userId: uuid(), createdAt: timestamp() }, ['id', 'userId', 'createdAt'])), '400': error('Invalid OIDC identity'), '404': error('Active user not found'), '409': error('OIDC identity already linked') } },
    },
    '/admin/oidc-identities/{id}': { delete: { summary: 'Unlink an OIDC identity', description: 'Requires site administrator. Revokes all sessions and tokens for the target account and preserves its last configured login method.', tags: [adminTag], parameters: [pathId('id', 'OIDC identity ID.')], responses: { '200': ok(success, { success: true }), '404': error('OIDC identity not found'), '409': error('Cannot remove the last login method') } } },
    '/site/settings': {
      get: { summary: 'Read site settings', description: 'Requires site administrator.', tags: [adminTag], responses: { '200': ok(object({ landingDisabled: { type: 'boolean' }, mcpSseEnabled: { type: 'boolean' }, logo: nullable(object({ updatedAt: timestamp(), url: str() }, ['updatedAt', 'url'])) }, ['landingDisabled', 'mcpSseEnabled', 'logo'])) } },
      patch: { summary: 'Update site settings', description: 'Requires site administrator. Disabling MCP SSE closes active sessions.', tags: [adminTag], requestBody: body(object({ landingDisabled: { type: 'boolean' }, mcpSseEnabled: { type: 'boolean' } }, [], { additionalProperties: false, minProperties: 1 }), { mcpSseEnabled: true }), responses: { '200': ok(object({ landingDisabled: { type: 'boolean' }, mcpSseEnabled: { type: 'boolean' } }, ['landingDisabled', 'mcpSseEnabled'])), '403': error('Site administrator required') } },
    },
    '/mcp/sse': { get: { summary: 'Open MCP SSE transport', description: 'Disabled by default and enabled by a site administrator. Requires a personal bearer token; browser session cookies are not accepted. Sessions expire after 30 minutes.', tags: ['Integrations'], security: [{ bearer: [] }], responses: { '200': { description: 'MCP server-sent event stream', content: { 'text/event-stream': { schema: str() } } }, '401': error('Bearer token required'), '404': error('MCP SSE disabled'), '429': error('Too many MCP sessions') } } },
    '/mcp/messages': { post: { summary: 'Send an MCP SSE session message', description: 'Requires the same authenticated user as the SSE session. Token validity and account state are rechecked for every message.', tags: ['Integrations'], security: [{ bearer: [] }], parameters: [query('sessionId', str({ format: 'uuid' }), 'Session identifier supplied by the MCP SSE endpoint event.')], requestBody: body(object({}, [], { additionalProperties: true })), responses: { '202': response('MCP message accepted'), '400': error('Invalid MCP message'), '401': error('Bearer token required'), '404': error('MCP session not found') } } },
    '/site/logo': {
      get: { summary: 'Read custom logo bytes', tags: [adminTag], security: [], responses: { '200': response('PNG, JPEG, WebP, or SVG bytes'), '404': error('No custom logo') } },
      put: { summary: 'Upload custom logo', description: 'Requires site administrator. Base64-decoded content is limited to 300 KiB and to PNG, JPEG, WebP, or SVG.', tags: [adminTag], requestBody: body(object({ contentType: str({ enum: ['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml'] }), data: str({ format: 'byte', writeOnly: true }) }, ['contentType', 'data'], { additionalProperties: false }), { contentType: 'image/png', data: '[BASE64 IMAGE DATA]' }), responses: { '200': ok(object({ url: str(), updatedAt: timestamp() }, ['url', 'updatedAt'])), '400': error('Invalid logo'), '403': error('Site administrator required') } },
      delete: { summary: 'Remove custom logo', description: 'Requires site administrator.', tags: [adminTag], responses: { '200': ok(success, { success: true }), '404': error('No custom logo') } },
    },
    '/workspaces': {
      get: { summary: 'List workspace memberships', description: secured(), tags: [workspaceTag], responses: { '200': ok(array(object({}, [], { additionalProperties: true }))) } },
      post: { summary: 'Create a workspace', description: 'Requires authentication. The creator receives the protected Owner role.', tags: [workspaceTag], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }) }, ['name'], { additionalProperties: false }), { name: 'Product planning' }), responses: { '201': ok(ref('Workspace')), '403': error('Account unavailable') } },
    },
    '/workspaces/{wid}': {
      get: { summary: 'Workspace detail and authorized metadata', description: 'Requires workspace membership. Metadata arrays are permission-filtered.', tags: [workspaceTag], parameters: [wid], responses: { '200': ok(object({}, [], { additionalProperties: true })), '403': error('Workspace access denied') } },
      patch: { summary: 'Rename a workspace', description: secured('workspace:manage'), tags: [workspaceTag], parameters: [wid], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }) }, ['name'], { additionalProperties: false }), { name: 'Product operations' }), responses: { '200': ok(ref('Workspace')), '403': error('Permission denied') } },
      delete: { summary: 'Permanently delete a workspace', description: 'Requires the protected Owner role. All relational workspace contents are deleted atomically; detached storage objects enter the existing garbage-collection lifecycle.', tags: [workspaceTag], parameters: [wid], responses: { '200': ok(success, { success: true }), '403': error('Workspace owner required') } },
    },
    '/workspaces/{wid}/export': { get: { summary: 'Stream complete workspace export', description: secured('items:read'), tags: [workspaceTag], parameters: [wid], responses: { '200': response('Complete versioned JSON export; attachment metadata only, never attachment bytes or secrets', object({}, [], { additionalProperties: true })) } } },
    '/workspaces/{wid}/nodes': {
      get: { summary: 'List hierarchy nodes', description: 'Requires items:read or structure:write.', tags: [structureTag], parameters: [wid], responses: { '200': ok(array(ref('Node'))) } },
      post: { summary: 'Create a project, folder, or list', description: `${secured('structure:write')} Projects and standalone lists may use a null parent; folders and nested lists require a project or folder parent.`, tags: [structureTag], parameters: [wid], requestBody: body(ref('NodeCreate'), { name: 'Release backlog', kind: 'list', parentId: null, icon: 'checklist', color: 'orange' }), responses: { '201': ok(ref('Node')), '400': error('Invalid hierarchy placement'), '403': error('Permission denied') } },
    },
    '/workspaces/{wid}/nodes/{id}': {
      patch: { summary: 'Rename, move, or style a node', description: `${secured('structure:write')} Lists may move to workspace root; inherited statuses are materialized first. Other moves reject cycles, cross-workspace parents, incompatible inherited statuses, and hierarchy depth above 32.`, tags: [structureTag], parameters: [wid, pathId('id', 'Node ID in this workspace.')], requestBody: body(ref('NodePatch'), { name: 'Ready for review', icon: 'flag', color: 'green' }), responses: { '200': ok(ref('Node')), '400': error('Invalid node update'), '404': error('Node not found'), '409': error('Location changed; reload before moving') } },
      delete: { summary: 'Delete an empty node', description: secured('structure:write'), tags: [structureTag], parameters: [wid, pathId('id', 'Node ID in this workspace.')], responses: { '200': ok(success, { success: true }), '404': error('Node not found'), '409': error('Node must be empty before deletion') } },
    },
    '/workspaces/{wid}/documents': {
      get: { summary: 'List document hierarchy metadata', description: 'Requires document read/write or structure management access. Bodies are omitted.', tags: [documentsTag], parameters: [wid], responses: { '200': ok(array(object({ id: uuid(), workspaceId: uuid(), parentId: nullable(uuid()), parentDocumentId: nullable(uuid()), pagePlacement: nullable(str({ enum: ['page', 'subpage'] })), title: str(), createdAt: timestamp(), updatedAt: timestamp() }, ['id', 'workspaceId', 'parentId', 'parentDocumentId', 'pagePlacement', 'title', 'createdAt', 'updatedAt']))) } },
      post: { summary: 'Create a document', description: secured('documents:write'), tags: [documentsTag], parameters: [wid], requestBody: body(object({ title: str({ minLength: 1, maxLength: 300 }), body: str({ maxLength: 50000 }), parentId: nullable(uuid()) }, ['title'], { additionalProperties: false }), { title: 'Runbook', body: 'Start here.', parentId: null }), responses: { '201': ok(ref('Document')), '400': error('Invalid document placement') } },
    },
    '/workspaces/{wid}/documents/{id}': {
      get: { summary: 'Read a document', description: secured('documents:read'), tags: [documentsTag], parameters: [wid, pathId('id')], responses: { '200': ok(ref('Document')), '404': error('Document not found') } },
      patch: { summary: 'Update a document', description: 'Requires documents:read and documents:write.', tags: [documentsTag], parameters: [wid, pathId('id')], requestBody: body(object({ title: str({ minLength: 1, maxLength: 300 }), body: str({ maxLength: 50000 }), parentId: nullable(uuid()), expectedUpdatedAt: timestamp() }, ['expectedUpdatedAt'], { additionalProperties: false }), { body: 'Updated body', expectedUpdatedAt: '2026-09-10T00:00:00.000Z' }), responses: { '200': ok(ref('Document')), '409': error('Document changed; reload before saving') } },
      delete: { summary: 'Delete a document and its document subpages', description: 'Requires documents:delete. Nested document pages are deleted; linked tasks and task subtasks are preserved.', tags: [documentsTag], parameters: [wid, pathId('id')], responses: { '200': ok(object({ success: { type: 'boolean' }, unlinkedPages: { type: 'integer', minimum: 0 }, deletedSubpages: { type: 'integer', minimum: 0 } }, ['success', 'unlinkedPages', 'deletedSubpages'])) } },
    },
    '/workspaces/{wid}/documents/{id}/pages': {
      get: { summary: 'List a bounded document task-page tree', description: 'Requires documents:read and items:read. At most 500 complete tasks are rendered; total remains complete.', tags: [documentsTag], parameters: [wid, pathId('id')], responses: { '200': ok(object({ items: array(ref('Item'), { maxItems: 500 }), total: { type: 'integer', minimum: 0 }, truncated: { type: 'boolean' } }, ['items', 'total', 'truncated'])) } },
      post: { summary: 'Link a top-level task as a document page', description: 'Requires documents:write and items:read. A task may be linked to only one document.', tags: [documentsTag], parameters: [wid, pathId('id')], requestBody: body(object({ itemId: uuid(), position: { type: 'integer', minimum: 0, maximum: 1000000 } }, ['itemId'], { additionalProperties: false })), responses: { '201': ok(object({ documentId: uuid(), itemId: uuid(), position: { type: 'integer' } }, ['documentId', 'itemId', 'position'])), '409': error('Task is already linked') } },
    },
    '/workspaces/{wid}/documents/{id}/subpages': {
      get: { summary: 'List editable document pages', description: 'Requires documents:read. Returns up to 500 document pages under the containing root document while preserving the complete total.', tags: [documentsTag], parameters: [wid, pathId('id')], responses: { '200': ok(object({ rootId: uuid(), documents: array(object({ id: uuid(), workspaceId: uuid(), parentId: nullable(uuid()), parentDocumentId: uuid(), pagePlacement: str({ enum: ['page', 'subpage'] }), title: str(), createdAt: timestamp(), updatedAt: timestamp() }, ['id', 'workspaceId', 'parentId', 'parentDocumentId', 'pagePlacement', 'title', 'createdAt', 'updatedAt']), { maxItems: 500 }), total: { type: 'integer', minimum: 0 }, truncated: { type: 'boolean' } }, ['rootId', 'documents', 'total', 'truncated'])) } },
      post: { summary: 'Create an editable document page', description: 'Requires documents:write. Placement `page` creates a top-level page from the root document; `subpage` creates beneath the addressed document/page, up to 31 page levels.', tags: [documentsTag], parameters: [wid, pathId('id')], requestBody: body(object({ title: str({ minLength: 1, maxLength: 300 }), placement: str({ enum: ['page', 'subpage'] }) }, ['title'], { additionalProperties: false }), { title: 'New page', placement: 'page' }), responses: { '201': ok(ref('Document')) } },
    },
    '/workspaces/{wid}/documents/{id}/pages/{itemId}': { delete: { summary: 'Unlink a document page without deleting its task', description: 'Requires documents:write and items:read.', tags: [documentsTag], parameters: [wid, pathId('id'), pathId('itemId')], responses: { '200': ok(success) } } },
    '/workspaces/{wid}/documents/{id}/comments': {
      get: { summary: 'List document comments', description: secured('documents:read'), tags: [documentsTag], parameters: [wid, pathId('id')], responses: { '200': ok(array(ref('Comment'))) } },
      post: { summary: 'Add a document comment, reply, or inline thread', description: 'Requires documents:read and comments:create. Anchors are revision-checked UTF-16 ranges over the Markdown body.', tags: [documentsTag], parameters: [wid, pathId('id')], requestBody: body(object({ body: str({ minLength: 1, maxLength: 10000 }), parentId: nullable(uuid()), anchor: ref('CommentAnchorInput') }, ['body'], { additionalProperties: false })), responses: { '201': ok(ref('Comment')), '409': error('Selected text is stale') } },
    },
    '/workspaces/{wid}/documents/{id}/comments/{commentId}': { delete: { summary: 'Delete or purge a document comment', tags: [documentsTag], parameters: [wid, pathId('id'), pathId('commentId')], responses: { '200': ok(success) } } },
    '/workspaces/{wid}/documents/{id}/comments/{commentId}/reaction': { patch: { summary: 'Add or remove a document comment reaction', description: 'Requires documents:read and comments:create.', tags: [documentsTag], parameters: [wid, pathId('id'), pathId('commentId')], requestBody: body(object({ emoji: str({ enum: ['👍', '❤️', '😂', '🎉', '😕', '👀'] }), active: { type: 'boolean' } }, ['emoji', 'active'], { additionalProperties: false })), responses: { '200': ok(object({ emoji: str(), active: { type: 'boolean' }, count: { type: 'integer' } }, ['emoji', 'active', 'count'])) } } },
    '/workspaces/{wid}/items': {
      get: { summary: 'Stream all matching tasks', description: secured('items:read'), tags: [itemsTag], parameters: itemFilters, responses: { '200': response('Complete JSON task array streamed from a bounded-lifetime snapshot', array(ref('Item'))) } },
      post: { summary: 'Create a task', description: `${secured('items:write')} nodeId must be a list and status must belong to its effective workflow.`, tags: [itemsTag], parameters: [wid], requestBody: body(ref('ItemCreate'), { nodeId: '33333333-3333-4333-8333-333333333333', title: 'Prepare release notes', priority: 'high', tags: ['release'] }), responses: { '201': ok(ref('Item')), '400': error('Invalid task'), '404': error('Node or parent task not found') } },
    },
    '/workspaces/{wid}/items/page': { get: { summary: 'Cursor-paged tasks', description: secured('items:read'), tags: [itemsTag], parameters: [...itemFilters, query('limit', { type: 'integer', minimum: 1, maximum: 500, default: 200 }), query('cursor', str({ minLength: 1, maxLength: 1024 }), 'Opaque cursor bound to workspace and active filters; it is not a credential.')], responses: { '200': ok(object({ items: array(ref('Item')), nextCursor: nullable(str()) }, ['items', 'nextCursor'])), '400': error('Invalid item cursor') } } },
    '/workspaces/{wid}/items/bulk': { post: { summary: 'Archive or delete selected tasks atomically', description: 'Archive requires items:read and items:write; delete requires items:delete. Every target revision is checked and parent tasks require all subtasks in the same selection.', tags: [itemsTag], parameters: [wid], requestBody: body(object({ action: str({ enum: ['archive', 'delete'] }), items: array(object({ id: uuid(), expectedUpdatedAt: timestamp() }, ['id', 'expectedUpdatedAt'], { additionalProperties: false }), { minItems: 1, maxItems: 100, uniqueItems: true }) }, ['action', 'items'], { additionalProperties: false }), { action: 'archive', items: [{ id: '33333333-3333-4333-8333-333333333333', expectedUpdatedAt: '2026-09-08T10:00:00.000Z' }] }), responses: { '200': ok(object({ action: str({ enum: ['archive', 'delete'] }), affected: { type: 'integer', minimum: 1, maximum: 100 } }, ['action', 'affected'])), '404': error('Task not found'), '409': error('A task changed or has unselected subtasks') } } },
    '/workspaces/{wid}/items/import': { post: { summary: 'Import tasks atomically from JSON or CSV', description: `${secured('items:write')} Maximum 500 rows and 1,000,000 characters; a row failure rolls back the whole import.`, tags: [itemsTag], parameters: [wid], requestBody: body(object({ nodeId: uuid(), format: str({ enum: ['json', 'csv'] }), data: str({ maxLength: 1000000 }) }, ['nodeId', 'format', 'data'], { additionalProperties: false }), { nodeId: '33333333-3333-4333-8333-333333333333', format: 'json', data: '[{"title":"Imported task","priority":"medium"}]' }), responses: { '201': ok(object({ imported: { type: 'integer', minimum: 0, maximum: 500 }, ids: array(uuid(), { maxItems: 500 }) }, ['imported', 'ids'])), '400': error('Import validation failed') } } },
    '/workspaces/{wid}/items/export': { get: { summary: 'Export tasks as JSON or CSV', description: secured('items:read'), tags: [itemsTag], parameters: [wid, query('format', str({ enum: ['json', 'csv'], default: 'json' })), query('nodeId', uuid()), query('status', str({ maxLength: 64 })), query('search', str({ maxLength: 300 })), query('limit', { type: 'integer', minimum: 1, maximum: 5000, default: 1000 })], responses: { '200': response('Task array or CSV attachment') } } },
    '/workspaces/{wid}/items/{id}': {
      get: { summary: 'Get a task', description: secured('items:read'), tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], responses: { '200': ok(ref('Item')), '404': error('Task not found') } },
      patch: { summary: 'Update a task', description: 'Requires both items:read and items:write. Optional expectedUpdatedAt provides optimistic concurrency; omitted means last-write-wins.', tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], requestBody: body(ref('ItemPatch'), { title: 'Prepare final release notes', expectedUpdatedAt: '2026-09-08T10:00:00.000Z' }), responses: { '200': ok(ref('Item')), '400': error('Invalid task update'), '404': error('Task not found'), '409': error('Item changed; reload before saving') } },
      delete: { summary: 'Delete a task', description: secured('items:delete'), tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], responses: { '200': ok(success, { success: true }), '404': error('Task not found'), '409': error('Task has subtasks and cannot be deleted') } },
    },
    '/workspaces/{wid}/items/{id}/comments': {
      get: { summary: 'List task comments', description: secured('items:read'), tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], responses: { '200': ok(array(ref('Comment'))) } },
      post: { summary: 'Add a task comment, reply, or inline thread', description: 'Requires items:read and comments:create. Optional parentId must identify a comment on this task. Anchors are revision-checked UTF-16 ranges over the task description.', tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], requestBody: body(object({ body: str({ minLength: 1, maxLength: 10000 }), parentId: nullable(uuid()), anchor: ref('CommentAnchorInput') }, ['body'], { additionalProperties: false }), { body: 'Please review this task.', parentId: null }), responses: { '201': ok(ref('Comment')), '400': error('Invalid comment, reply depth, or mention'), '404': error('Task or parent comment not found'), '409': error('Selected text is stale') } },
    },
    '/workspaces/{wid}/items/{id}/comments/{commentId}': { delete: { summary: 'Delete a comment or remove its tombstone', description: 'The author or comments:manage may replace a live comment with a tombstone. A subsequent call requires comments:manage and permanently removes that deleted entry while preserving its replies.', tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.'), pathId('commentId', 'Comment ID on this task.')], responses: { '200': ok(success, { success: true }), '403': error('Comment author or comments manager required'), '404': error('Comment not found') } } },
    '/workspaces/{wid}/items/{id}/comments/{commentId}/reaction': { patch: { summary: 'Add or remove the current member reaction', description: 'Requires items:read and comments:create. Reactions are unique per member, comment, and emoji.', tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.'), pathId('commentId', 'Comment ID on this task.')], requestBody: body(object({ emoji: str({ enum: ['👍', '❤️', '😂', '🎉', '😕', '👀'] }), active: { type: 'boolean' } }, ['emoji', 'active'], { additionalProperties: false }), { emoji: '👍', active: true }), responses: { '200': ok(object({ emoji: str(), active: { type: 'boolean' }, count: { type: 'integer', minimum: 0 } }, ['emoji', 'active', 'count'])), '404': error('Comment not found'), '409': error('Deleted comments cannot receive reactions') } } },
    '/workspaces/{wid}/notifications': { get: { summary: 'List the current member notifications', description: secured('items:read'), tags: [itemsTag], parameters: [wid], responses: { '200': ok(array(ref('Notification'))) } } },
    '/workspaces/{wid}/notifications/unread-count': { get: { summary: 'Count the current member unread notifications', description: secured('items:read'), tags: [itemsTag], parameters: [wid], responses: { '200': ok(object({ unread: { type: 'integer', minimum: 0 } }, ['unread'])) } } },
    '/workspaces/{wid}/notifications/{id}': {
      patch: { summary: 'Mark an owned notification read or unread', description: secured('items:read'), tags: [itemsTag], parameters: [wid, pathId('id', 'Notification ID owned by the current member.')], requestBody: body(object({ read: { type: 'boolean' } }, ['read'], { additionalProperties: false }), { read: true }), responses: { '200': ok(object({ id: uuid(), readAt: nullable(timestamp()) }, ['id', 'readAt'])), '404': error('Notification not found') } },
      delete: { summary: 'Delete an owned notification', description: secured('items:read'), tags: [itemsTag], parameters: [wid, pathId('id', 'Notification ID owned by the current member.')], responses: { '200': ok(success, { success: true }), '404': error('Notification not found') } },
    },
    '/workspaces/{wid}/fields': {
      get: { summary: 'List workspace field definitions', description: 'Requires items:read or structure:write.', tags: [structureTag], parameters: [wid], responses: { '200': ok(array(ref('Field'))) } },
      post: { summary: 'Create a field definition', description: `${secured('structure:write')} Optional projectId identifies a root project or standalone list and creates the assignment atomically.`, tags: [structureTag], parameters: [wid], requestBody: body(ref('FieldCreate'), { name: 'Effort', type: 'rating', settings: { maxRating: 5 } }), responses: { '201': ok(ref('Field')), '400': error('Invalid field definition') } },
    },
    '/workspaces/{wid}/fields/{id}': {
      patch: { summary: 'Update a field definition', description: `${secured('structure:write')} Field type cannot change; updates that invalidate stored values or formula references are rejected.`, tags: [structureTag], parameters: [wid, pathId('id', 'Field ID in this workspace.')], requestBody: body(ref('FieldPatch'), { name: 'Delivery effort', settings: { maxRating: 5 } }), responses: { '200': ok(ref('Field')), '404': error('Field not found'), '409': error('Field update conflicts with stored values or formulas') } },
      delete: { summary: 'Delete a field and its values', description: `${secured('structure:write')} Also removes assignments and task values; referenced fields cannot be deleted.`, tags: [structureTag], parameters: [wid, pathId('id', 'Field ID in this workspace.')], responses: { '200': ok(success, { success: true }), '404': error('Field not found'), '409': error('Field is referenced by a formula') } },
    },
    '/workspaces/{wid}/projects/{projectId}/fields': {
      get: { summary: 'Read field-owner configuration', description: 'Requires items:read or structure:write. The target must be a root project or standalone root list.', tags: [structureTag], parameters: [wid, pathId('projectId', 'Root project or standalone list ID in this workspace.')], responses: { '200': ok(ref('ProjectFields')) } },
      patch: { summary: 'Update fields, workflow, or date format', description: `${secured('structure:write')} The target may be a root project or standalone list. Standalone workflows remain managed by the list-status endpoint. Optional expectedUpdatedAt protects against concurrent updates; project statuses in use cannot be removed. Null dateFormat restores the default.`, tags: [structureTag], parameters: [wid, pathId('projectId', 'Root project or standalone list ID in this workspace.')], requestBody: body(object({ fieldIds: array(uuid(), { maxItems: 100, uniqueItems: true }), builtInFields: array(str({ enum: ['priority', 'startDate', 'tags', 'description', 'nodeId', 'createdAt', 'updatedAt'] }), { maxItems: 7, uniqueItems: true }), statuses: array(ref('Status'), { minItems: 1, maxItems: 50 }), dateFormat: nullable(str({ enum: ['yyyy-MM-dd', 'MMM d, yyyy', 'MMMM d, yyyy', 'dd/MM/yyyy'] })), expectedUpdatedAt: timestamp() }, [], { additionalProperties: false, anyOf: [{ required: ['fieldIds'] }, { required: ['builtInFields'] }, { required: ['statuses'] }, { required: ['dateFormat'] }] }), { builtInFields: ['priority', 'tags'], expectedUpdatedAt: '2026-09-08T10:00:00.000Z' }), responses: { '200': ok(ref('ProjectFields')), '400': error('Invalid field-owner configuration'), '409': error('Field configuration changed or statuses remain in use') } },
    },
    '/workspaces/{wid}/views/list/settings': {
      get: { summary: "Read the authenticated member's List settings", description: secured('items:read'), tags: [itemsTag], parameters: [wid, query('projectId', uuid(), 'Root project or standalone-list field scope; omit for workspace-wide scope.')], responses: { '200': ok(ref('ListViewSettings')) } },
      patch: { summary: "Replace the authenticated member's List settings", description: `${secured('items:read')} Identity always comes from authentication. expectedUpdatedAt must be null when creating or exactly match the stored revision.`, tags: [itemsTag], parameters: [wid], requestBody: body(object({ projectId: nullable(uuid()), columnOrder: array(str({ maxLength: 43 }), { maxItems: 111, uniqueItems: true }), hiddenColumns: array(str({ maxLength: 43 }), { maxItems: 110, uniqueItems: true }), sort: listSortSchema, expectedUpdatedAt: nullable(timestamp()) }, ['columnOrder', 'hiddenColumns', 'sort', 'expectedUpdatedAt'], { additionalProperties: false }), { projectId: null, columnOrder: ['title', 'status', 'dueDate'], hiddenColumns: [], sort: { column: 'dueDate', direction: 'asc' }, expectedUpdatedAt: null }), responses: { '200': ok(ref('ListViewSettings')), '400': error('Invalid List settings'), '409': error('List view settings changed; reload before saving') } },
    },
    '/workspaces/{wid}/lists/{listId}/statuses': {
      get: { summary: 'Read a list workflow override or inheritance state', description: 'Requires items:read or structure:write. Standalone root lists always return explicit statuses and omit inheritedProjectUpdatedAt.', tags: [structureTag], parameters: [wid, pathId('listId', 'List ID in this workspace.')], responses: { '200': ok(ref('ListStatuses')) } },
      patch: { summary: 'Set or clear a list workflow override', description: `${secured('structure:write')} null restores project inheritance and is invalid for a standalone root list. Enabling an override from inheritance requires the current project revision.`, tags: [structureTag], parameters: [wid, pathId('listId', 'List ID in this workspace.')], requestBody: body(object({ statuses: nullable(array(ref('Status'), { minItems: 1, maxItems: 50 })), expectedUpdatedAt: timestamp(), expectedProjectUpdatedAt: timestamp() }, ['statuses'], { additionalProperties: false }), { statuses: null, expectedUpdatedAt: '2026-09-08T10:00:00.000Z' }), responses: { '200': ok(ref('ListStatuses')), '400': error('Invalid list workflow'), '409': error('List or project statuses changed') } },
    },
    '/workspaces/{wid}/lists/{listId}/tag-colors': {
      get: { summary: 'Read per-list tag colors', description: 'Requires items:read or structure:write.', tags: [structureTag], parameters: [wid, pathId('listId', 'List ID in this workspace.')], responses: { '200': ok(ref('ListTagColors')) } },
      patch: { summary: 'Replace per-list tag colors', description: `${secured('structure:write')} Up to 30 trimmed tag names map to six-digit hex colors. expectedUpdatedAt is mandatory.`, tags: [structureTag], parameters: [wid, pathId('listId', 'List ID in this workspace.')], requestBody: body(object({ colors: tagColorsMap, expectedUpdatedAt: timestamp() }, ['colors', 'expectedUpdatedAt'], { additionalProperties: false }), { colors: { release: '#e36b24', blocked: '#b42318' }, expectedUpdatedAt: '2026-09-08T10:00:00.000Z' }), responses: { '200': ok(ref('ListTagColors')), '400': error('Invalid tag color map'), '409': error('List tag colors changed; reload before saving') } },
    },
    '/workspaces/{wid}/members': { post: { summary: 'Add an existing active account to a workspace', description: `${secured('members:manage')} The actor cannot grant permissions they do not hold.`, tags: [workspaceTag], parameters: [wid], requestBody: body(object({ email: str({ format: 'email', maxLength: 254 }), roleId: uuid() }, ['email', 'roleId'], { additionalProperties: false }), { email: 'member@example.test', roleId: '44444444-4444-4444-8444-444444444444' }), responses: { '201': ok(ref('Membership')), '403': error('Permission denied'), '404': error('Active user not found') } } },
    '/workspaces/{wid}/members/{userId}': {
      patch: { summary: 'Change a member role', description: `${secured('members:manage')} Permission escalation and removal of the last active Owner are rejected.`, tags: [workspaceTag], parameters: [wid, pathId('userId', 'Member user ID.')], requestBody: body(object({ roleId: uuid() }, ['roleId'], { additionalProperties: false }), { roleId: '44444444-4444-4444-8444-444444444444' }), responses: { '200': ok(ref('Membership')), '404': error('Member not found'), '409': error('Workspace must retain an active Owner') } },
      delete: { summary: 'Remove a workspace member', description: `${secured('members:manage')} Clears this member's assignments and protects the last active Owner.`, tags: [workspaceTag], parameters: [wid, pathId('userId', 'Member user ID.')], responses: { '200': ok(success, { success: true }), '404': error('Member not found'), '409': error('Workspace must retain an active Owner') } },
    },
    '/workspaces/{wid}/roles': {
      get: { summary: 'List roles visible to the caller', description: 'Requires workspace membership; the catalog is permission-filtered.', tags: [workspaceTag], parameters: [wid], responses: { '200': ok(array(ref('Role'))) } },
      post: { summary: 'Create a role', description: `${secured('roles:manage')} The actor cannot grant permissions they do not hold.`, tags: [workspaceTag], parameters: [wid], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }), permissions: array(str({ enum: [...permissions] }), { maxItems: permissions.length, uniqueItems: true }) }, ['name', 'permissions'], { additionalProperties: false }), { name: 'Editor', permissions: ['items:read', 'items:write'] }), responses: { '201': ok(ref('Role')), '403': error('Permission denied') } },
    },
    '/workspaces/{wid}/roles/{id}': {
      patch: { summary: 'Update a role', description: `${secured('roles:manage')} The Owner role is protected and permission escalation is rejected.`, tags: [workspaceTag], parameters: [wid, pathId('id', 'Role ID in this workspace.')], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }), permissions: array(str({ enum: [...permissions] }), { maxItems: permissions.length, uniqueItems: true }) }, [], { additionalProperties: false }), { permissions: ['items:read', 'items:write'] }), responses: { '200': ok(ref('Role')), '403': error('Owner role is protected'), '404': error('Role not found') } },
      delete: { summary: 'Delete an unassigned role', description: `${secured('roles:manage')} The Owner role is protected.`, tags: [workspaceTag], parameters: [wid, pathId('id', 'Role ID in this workspace.')], responses: { '200': ok(success, { success: true }), '403': error('Owner role is protected'), '409': error('Role is assigned to members') } },
    },
    '/workspaces/{wid}/webhooks': {
      get: { summary: 'List webhooks', description: secured('workspace:manage'), tags: [automationsTag], parameters: [wid], responses: { '200': ok(array(ref('Webhook'))) } },
      post: { summary: 'Create a webhook', description: `${secured('workspace:manage')} Maximum 20 per workspace. The signing secret is returned once and never appears in list responses.`, tags: [automationsTag], parameters: [wid], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }), url: str({ format: 'uri', maxLength: 2000 }), events: array(event, { minItems: 1, maxItems: events.length }), enabled: { type: 'boolean', default: true } }, ['name', 'url', 'events'], { additionalProperties: false }), { name: 'Issue mirror', url: 'https://hooks.example.test/hopya', events: ['item.created'], enabled: true }), responses: { '200': ok({ allOf: [ref('Webhook'), object({ secret: str({ writeOnly: true }) }, ['secret'])] }, { id: '55555555-5555-4555-8555-555555555555', name: 'Issue mirror', url: 'https://hooks.example.test/hopya', events: ['item.created'], enabled: true, signingVersion: 2, secret: '[REDACTED]', createdAt: '2026-09-08T10:00:00.000Z', updatedAt: '2026-09-08T10:00:00.000Z' }), '400': error('Invalid webhook') } },
    },
    '/workspaces/{wid}/webhooks/{id}': {
      patch: { summary: 'Update a webhook', description: secured('workspace:manage'), tags: [automationsTag], parameters: [wid, pathId('id', 'Webhook ID in this workspace.')], requestBody: body(object({ name: str({ minLength: 1, maxLength: 120 }), url: str({ format: 'uri', maxLength: 2000 }), events: array(event, { minItems: 1, maxItems: events.length }), enabled: { type: 'boolean' } }, [], { additionalProperties: false }), { enabled: false }), responses: { '200': ok(ref('Webhook')), '404': error('Webhook not found') } },
      delete: { summary: 'Delete a webhook and its run history', description: secured('workspace:manage'), tags: [automationsTag], parameters: [wid, pathId('id', 'Webhook ID in this workspace.')], responses: { '200': ok(success, { success: true }), '404': error('Webhook not found') } },
    },
    '/workspaces/{wid}/webhooks/{id}/rotate': { post: { summary: 'Rotate a webhook signing secret', description: `${secured('workspace:manage')} The replacement secret is returned once and signingVersion is set to 2.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Webhook ID in this workspace.')], responses: { '200': ok(object({ secret: str({ writeOnly: true }), signingVersion: { type: 'integer', const: 2 } }, ['secret', 'signingVersion']), { secret: '[REDACTED]', signingVersion: 2 }), '404': error('Webhook not found') } } },
    '/workspaces/{wid}/automations': {
      get: { summary: 'List linear and graph automations', description: `${secured('automations:manage')} Linear automations include ordered steps; published graph automations expose graph=true instead of a flattened step list.`, tags: [automationsTag], parameters: [wid], responses: { '200': ok(array(ref('Automation'))) } },
      post: { summary: 'Create a legacy linear automation', description: `${secured('automations:manage')} Maximum 50 per workspace. Supply exactly one legacy action or an ordered 1-20 step list; references may use only prior \`{{steps.N.output}}\` values. The resulting linear version is also available as a graph through the version and draft routes.`, tags: [automationsTag], parameters: [wid], requestBody: body(ref('AutomationInput'), { name: 'Record and notify', event: 'item.created', steps: actionExamples, enabled: true }), responses: { '200': ok(ref('Automation')), '400': error('Invalid automation or step sequence') } },
    },
    '/workspaces/{wid}/automations/{id}': {
      patch: { summary: 'Update automation metadata or legacy steps', description: `${secured('automations:manage')} Replacing action/steps or changing the event on a linear automation creates a new immutable linear version. Published graphs reject legacy action, steps, and event changes with 409; change their trigger through a graph draft. Name and enabled remain patchable.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.')], requestBody: body(ref('AutomationPatch'), { steps: [{ type: 'log', config: { message: 'Automation revision two' } }], enabled: true }), responses: { '200': ok(ref('Automation')), '400': error('Invalid automation or step sequence'), '404': error('Automation not found'), '409': error('Published graph cannot be changed through the legacy API') } },
      delete: { summary: 'Delete an automation and its run history', description: secured('automations:manage'), tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.')], responses: { '200': ok(success, { success: true }), '404': error('Automation not found') } },
    },
    '/workspaces/{wid}/automations/catalog': { get: { summary: 'Read graph node and event descriptors', description: `${secured('automations:manage')} Returns server-owned graph limits plus typed node manifests used by editors and data pickers.`, tags: [automationsTag], parameters: [wid], responses: { '200': ok(ref('AutomationCatalog')) } } },
    '/workspaces/{wid}/automations/{id}/draft': {
      get: { summary: 'Read the current graph draft', description: `${secured('automations:manage')} If no draft exists, returns revision 0 with the current published version graph and updatedAt null.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.')], responses: { '200': ok(ref('AutomationDraft')), '404': error('Automation not found') } },
      put: { summary: 'Save a graph draft with optimistic concurrency', description: `${secured('automations:manage')} Draft changes do not affect queued, active, or published versions. expectedRevision must match the current draft revision. Structural validation is reported in the response but invalid drafts may still be saved.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.')], requestBody: body(object({ expectedRevision: { type: 'integer', minimum: 0 }, graph: ref('AutomationGraph') }, ['expectedRevision', 'graph'], { additionalProperties: false })), responses: { '200': ok(ref('AutomationDraftSaved')), '400': error('Invalid graph shape'), '404': error('Automation not found'), '409': error('Draft changed; reload before saving') } },
    },
    '/workspaces/{wid}/automations/{id}/validate': { post: { summary: 'Validate a supplied or saved draft graph', description: `${secured('automations:manage')} Omit graph to validate the saved draft. Includes graph structure, control flow, upstream references, destination safety, and active workspace credential bindings.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.')], requestBody: body(object({ graph: ref('AutomationGraph') }, [], { additionalProperties: false })), responses: { '200': ok(ref('GraphValidation')), '400': error('No valid graph was supplied or saved'), '404': error('Automation not found') } } },
    '/workspaces/{wid}/automations/{id}/publish': { post: { summary: 'Publish the current graph draft', description: `${secured('automations:manage')} Validates the exact draft revision and active credential bindings, creates an immutable graph version, changes the trigger event to the graph trigger, and retains the draft while atomically advancing its revision by one. Revisions remain monotonic across save/publish cycles; stale requests return 409. Returns the published version, not the draft; re-read the draft for its current revision. Queued and active runs are unchanged.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.')], requestBody: body(object({ expectedRevision: { type: 'integer', minimum: 1 } }, ['expectedRevision'], { additionalProperties: false }), { expectedRevision: 1 }), responses: { '200': ok(ref('AutomationVersion')), '400': error('Graph or credential binding is invalid'), '404': error('Automation not found'), '409': error('Draft changed; reload before publishing') } } },
    '/workspaces/{wid}/automations/{id}/versions': { get: { summary: 'List immutable published versions', description: secured('automations:manage'), tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.')], responses: { '200': ok(array(ref('AutomationVersionSummary'))), '404': error('Automation not found') } } },
    '/workspaces/{wid}/automations/{id}/versions/{version}': { get: { summary: 'Read one immutable published graph representation', description: `${secured('automations:manage')} Both graph and legacy linear versions are represented as nodes and edges; format identifies their source form.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.'), version], responses: { '200': ok(ref('AutomationVersion')), '404': error('Automation version not found') } } },
    '/workspaces/{wid}/automations/{id}/preview': { post: { summary: 'Preview graph control flow without side effects', description: `${secured('automations:manage')} Uses the supplied graph or current published graph, an optional event, and optional node mock outputs. Actions are simulated with typed outputs; routing stops with an uncertainty marker when a control node depends on an unknown output. Every returned path entry has effect=none.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.')], requestBody: body(object({ graph: ref('AutomationGraph'), event: object({}, [], { additionalProperties: true, default: {} }), mockOutputs: object({}, [], { propertyNames: graphNodeId, additionalProperties: true, default: {} }) }, [], { additionalProperties: false })), responses: { '200': ok(ref('GraphPreview')), '400': error('Invalid graph or preview event'), '404': error('Automation not found') } } },
    '/workspaces/{wid}/automations/{id}/test': { post: { summary: 'Queue a test run of the current automation version', description: `${secured('automations:manage')} The test is asynchronous and may perform real configured effects. Its synthetic event contains no task target, so a published graph containing any update_item node is rejected with 400 before enqueueing, even on an unselected branch. Use a real task event for those graphs. Monitor accepted runId through the run endpoint.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Automation ID in this workspace.')], responses: { '200': ok(object({ ok: { type: 'boolean', const: true }, event, runId: uuid(), status: { type: 'string', const: 'pending' } }, ['ok', 'event', 'runId', 'status']), { ok: true, event: 'item.created', runId: '66666666-6666-4666-8666-666666666666', status: 'pending' }), '400': error('Test runs have no triggering task; use a real task event for Update task graphs'), '404': error('Automation not found') } } },
    '/workspaces/{wid}/automations/runs': { get: { summary: 'Monitor recent automation and webhook runs', description: `${secured('automations:manage')} Returns at most 100 sanitized records. Linear step runs and graph node runs are separate arrays; raw queued event payloads, credentials, and secrets are omitted.`, tags: [automationsTag], parameters: [wid, query('limit', { type: 'integer', minimum: 1, maximum: 100, default: 20 }), query('automationId', uuid(), 'Automation ID; webhook runs are not selected by this filter.'), query('status', str({ enum: ['pending', 'running', 'delivered', 'failed'] }))], responses: { '200': ok(array(ref('AutomationRun'))), '400': error('Invalid run filter') } } },
    '/workspaces/{wid}/automations/runs/{runId}': { get: { summary: 'Read one automation or webhook run', description: `${secured('automations:manage')} Step and node outputs/logs are bounded and sanitized; the raw event payload is omitted.`, tags: [automationsTag], parameters: [wid, pathId('runId', 'Run ID in this workspace.')], responses: { '200': ok(ref('AutomationRun')), '404': error('Automation run not found') } } },
    '/workspaces/{wid}/automations/credentials': {
      get: { summary: 'List automation credential metadata', description: 'Requires automations:manage or credentials:manage. Secret values and encrypted material are never returned.', tags: [automationsTag], parameters: [wid], responses: { '200': ok(array(ref('AutomationCredential'))) } },
      post: { summary: 'Create a bound automation credential', description: `${secured('credentials:manage')} Stores a new encrypted credential version. origin contains only scheme, host, and optional port; pathPrefix optionally narrows where it may be sent. Public credential destinations require HTTPS unless explicitly allowed by the operator.`, tags: [automationsTag], parameters: [wid], requestBody: body(ref('AutomationCredentialCreate'), { name: 'Service bearer', type: 'bearer', origin: 'https://api.example.test', pathPrefix: '/v1/tasks', secret: { token: '[REDACTED]' } }), responses: { '200': ok(ref('AutomationCredential')), '400': error('Credential or destination binding is invalid'), '503': error('Automation credential keyring is unavailable') } },
    },
    '/workspaces/{wid}/automations/credentials/{id}': {
      get: { summary: 'Read automation credential metadata', description: 'Requires automations:manage or credentials:manage. Secret values and encrypted material are never returned.', tags: [automationsTag], parameters: [wid, pathId('id', 'Credential ID in this workspace.')], responses: { '200': ok(ref('AutomationCredential')), '404': error('Credential not found') } },
      put: { summary: 'Replace an active credential secret', description: `${secured('credentials:manage')} expectedVersion provides optimistic concurrency. Type, origin, and pathPrefix are immutable; the optional name and type-specific secret are replaced in a new encrypted version.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Credential ID in this workspace.')], requestBody: body(ref('AutomationCredentialReplace'), { expectedVersion: 1, name: 'Service bearer', secret: { token: '[REDACTED]' } }), responses: { '200': ok(ref('AutomationCredential')), '400': error('Credential secret is invalid'), '404': error('Active credential not found'), '409': error('Credential changed; reload before replacing'), '503': error('Automation credential keyring is unavailable') } },
      delete: { summary: 'Revoke an automation credential', description: `${secured('credentials:manage')} Marks the credential revoked; metadata remains available and future execution cannot use it.`, tags: [automationsTag], parameters: [wid, pathId('id', 'Credential ID in this workspace.')], responses: { '200': ok(success, { success: true }), '404': error('Credential not found') } },
    },
    '/workspaces/{wid}/automations/credentials/{id}/oauth/start': { post: { summary: 'Start OAuth 2.0 authorization-code connection', description: `${secured('credentials:manage')} Requires an active oauth2 credential. Creates a single-user, ten-minute PKCE flow and returns the provider authorization URL.`, tags: [automationsTag], parameters: [wid, pathId('id', 'OAuth credential ID in this workspace.')], responses: { '200': ok(object({ authorizationUrl: str({ format: 'uri' }), expiresAt: timestamp() }, ['authorizationUrl', 'expiresAt'], { additionalProperties: false })), '400': error('Credential is not OAuth 2.0 or its destination is invalid'), '404': error('Credential not found'), '503': error('Automation credential keyring is unavailable') } } },
    '/workspaces/{wid}/automations/credentials/{id}/oauth/callback': { get: { summary: 'Complete OAuth 2.0 authorization-code connection', description: `${secured('credentials:manage')} Consumes the authenticated user's one-time PKCE state, exchanges the code without redirects, and stores tokens only in a new encrypted credential version.`, tags: [automationsTag], parameters: [wid, pathId('id', 'OAuth credential ID in this workspace.'), { ...query('state', str({ minLength: 20, maxLength: 200, writeOnly: true })), required: true }, { ...query('code', str({ minLength: 1, maxLength: 4000, writeOnly: true })), required: true }], responses: { '302': response('Redirect to /integrations?oauth=connected'), '400': error('OAuth state is invalid, expired, or malformed'), '409': error('OAuth credential changed; start the connection again'), '502': error('OAuth token exchange failed'), '503': error('Automation credential keyring is unavailable') } } },
    '/workspaces/{wid}/agent': { post: { summary: 'Ask the optional AI assistant', description: 'Requires both agent:use and items:read. Context is bounded to 100 recent tasks and 100 lists. The response can only propose a task; mutations require separate explicit human confirmation through task routes.', tags: [automationsTag], parameters: [wid], requestBody: body(object({ message: str({ minLength: 1, maxLength: 8000 }) }, ['message'], { additionalProperties: false }), { message: 'Summarize current release work and suggest one next task.' }), responses: { '200': ok(object({ reply: str({ minLength: 1, maxLength: 16000 }), proposal: nullable(object({ title: str({ maxLength: 300 }), description: str({ maxLength: 10000 }), nodeId: uuid(), dueDate: date, priority }, ['title'], { additionalProperties: false })) }, ['reply'])), '429': error('Assistant is busy'), '502': error('AI provider failed; no tasks were changed'), '503': error('AI assistant is disabled') } } },
    '/workspaces/{wid}/items/{id}/attachments': {
      get: { summary: 'List task attachments', description: secured('items:read'), tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], responses: { '200': ok(array(ref('Attachment'))) } },
      post: { summary: 'Upload a task attachment', description: `${secured('items:write')} Base64-decoded content is limited to 10 MiB; filenames and storage object keys are validated independently.`, tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.')], requestBody: body(object({ name: str({ minLength: 1, maxLength: 255 }), contentType: str({ maxLength: 127 }), data: str({ format: 'byte', writeOnly: true }) }, ['name', 'contentType', 'data'], { additionalProperties: false }), { name: 'release-notes.txt', contentType: 'text/plain', data: '[BASE64 FILE DATA]' }), responses: { '201': ok(ref('Attachment')), '400': error('Invalid attachment'), '413': error('Attachment exceeds 10 MiB'), '503': error('Attachment storage unavailable') } },
    },
    '/workspaces/{wid}/items/{id}/attachments/{attachmentId}': {
      get: { summary: 'Download an attachment', description: secured('items:read'), tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.'), pathId('attachmentId', 'Attachment ID on this task.')], responses: { '200': response('Attachment bytes with forced download disposition'), '404': error('Attachment not found'), '503': error('Attachment storage unavailable') } },
      delete: { summary: 'Delete an attachment', description: `${secured('items:delete')} Access is revoked before best-effort physical cleanup.`, tags: [itemsTag], parameters: [wid, pathId('id', 'Task ID in this workspace.'), pathId('attachmentId', 'Attachment ID on this task.')], responses: { '200': ok(object({ success: { type: 'boolean', const: true }, cleanupPending: { type: 'boolean' } }, ['success', 'cleanupPending']), { success: true, cleanupPending: false }), '404': error('Attachment not found') } },
    },
  }
}

export function openApiDocument() {
  return Effect.runSync(documentEffect())
}

const documentEffect = () => Effect.sync(() => ({
  openapi: '3.1.0',
  info: {
    title: 'Hopya API', version: '1.0.0',
    description: 'Self-hosted task management API. Browser clients use HttpOnly session cookies and same-origin checks for mutations; programmatic clients use revocable bearer tokens. Workspace IDs and resource IDs never grant access by themselves.',
  },
  servers: [{ url: '/api/v1' }],
  components: {
    securitySchemes: {
      bearer: { type: 'http', scheme: 'bearer', description: 'Raw API token returned once by POST /auth/tokens.' },
      session: { type: 'apiKey', in: 'cookie', name: 'hopya_session', description: 'HttpOnly browser session; unsafe requests also require a matching Origin.' },
    },
    schemas,
  },
  security: auth,
  tags: [workspaceTag, itemsTag, structureTag, automationsTag, adminTag, 'Meta'].map((name) => ({ name })),
  paths: paths(),
  'x-hopya-permissions': permissions,
}))
